### PR TITLE
fix crash in SmilesGenerator when calling with reaction not having one or more reaction components

### PR DESCRIPTION
**Pull request by uli-f**
Without the change in `SmilesGenerator::String create(IReaction,int[])` the test method `EmptyReactionSmilesGenerationTest.java::emptyReactionInstance_smilesFlavorCanonicalStereo_test` fails.

### CODE REVIEW

**Comment by uli-f** [comment]
@johnmay I am also not sure if the return value of `>>` for a completely empty reaction is desirable. Personally, I would expect `''`.

**Comment by johnmay** [comment]
> @johnmay I am also not sure if the return value of `>>` for a completely empty reaction is desirable. Personally, I would expect `''`.

So the idea is you have no info, except that it is a reaction!

**Comment by johnmay** [comment]
A looks good, but not clear to me why it fails? The sub-method should return an empty string - I actually think the cleaner fix would be to make the test on entry to that method?

**Comment by uli-f** [comment]
> All looks good, but not clear to me why it fails? The sub-method should return an empty string - I actually think the cleaner fix would be to make the test on entry to that method?

Good question! I drilled down a bit more downstream:
- I reversed the changes in `SmilesGenerator`.
- Instead, I fixed the issue in InChINumbersTools::getUSmilesNumbers

Is there a reason to use reflection in `SmilesGenerator::inchiNumbers` instead of just calling `InChINumbersTools::getUSmilesNumbers`? 🤔

**Comment by uli-f** [comment]
fixes #959

**Comment by johnmay** [comment]
No circular dependency we just don’t want to avoid pulling in the inchi unless absolutely needed - we should perhaps make it an optional decency which I only now know is a thing.

I should also just write a better default canonical labelling which does stereochemistry

**Pull request merged**
