### PR TITLE
PerceiveStereo option for Bayesian class

### PR DESCRIPTION
**Pull request by kazuyaujihara**
A flag whether to perceive stereo or not is added to Bayesian class.
Rolling back CircularFingerprinter.rubricTetrahedral(int) method is also included.

### CODE REVIEW

**Comment by johnmay** [comment]
What's the rollback for?

**Comment by kazuyaujihara** [comment]
A calculated relative x-position of implicit H of 'atom' should be stored in 'xp[3]' at the following of "// build an implicit H if necessary" line. 'x0' is just the absolute x-position of 'atom' here. 
The previous code looks good.

**Comment by johnmay** [comment]
See #377, you get the wrong answer if you use that method. The better way is to use the XYZ of chiral atom.

**Comment by kazuyaujihara** [comment]
I understood using XYZ is better. Thanks.
But, I believe  

            xp[3] = x0;
            yp[3] = y0;
            zp[3] = z0;

 is corrected to

            xp[3] = 0;
            yp[3] = 0;
            zp[3] = 0;

because (xp, yp, zp) is relative position in this context .
In fact, it fails the following test.

    @Test
    public void testNonZZeroPlaner() throws Exception {
        IAtomContainer mol = new AtomContainer();
        Atom[] atoms = new Atom[] {
            new Atom("C"),
            new Atom("F"),
            new Atom("N"),
            new Atom("O"),
        };
        atoms[0].setPoint3d(new Point3d(0, 0, -10));
        atoms[1].setPoint3d(new Point3d(0, 1, -10));
        atoms[2].setPoint3d(new Point3d(-1, -1, -10));
        atoms[3].setPoint3d(new Point3d(1, -1, -10));
        mol.setAtoms(atoms);
        mol.addBond(0, 1, IBond.Order.SINGLE);
        mol.addBond(0, 2, IBond.Order.SINGLE);
        mol.addBond(0, 3, IBond.Order.SINGLE);
        mol.getBond(0).setStereo(IBond.Stereo.UP);
        
        CircularFingerprinter circ = new CircularFingerprinter(CircularFingerprinter.CLASS_ECFP6);
        circ.setPerceiveStereo(true);
        IBitFingerprint fp0 = circ.getBitFingerprint(mol);
        
        for (int i = 0; i < atoms.length; i++) {
            Point3d p = atoms[i].getPoint3d();
            atoms[i].setPoint3d(new Point3d(p.getX(), p.getY(), p.getZ() + 20));
        }

        IBitFingerprint fp1 = circ.getBitFingerprint(mol);
        
        Assert.assertThat(fp0, is(fp1));
    }

**Comment by johnmay** [comment]
Yep you're right, could you make the patch for:
```java
        xp[3] = 0;
        yp[3] = 0;
        zp[3] = 0;
```
and I'll pull that in.

**Comment by johnmay** [comment]
Perfect, thanks!

**Pull request merged**
