### PR TITLE
Merged the last bits of cdk-annotation into cdk-ioformats

### PR DESCRIPTION
**Pull request by egonw**

### CODE REVIEW

**Comment by egonw** [comment]
Argh... local Maven repository cache... I'm fixing this...

**Comment by johnmay** [comment]
Unfortunately for compatibility the core/annotation/pom.xml needs to stay in place as an empty module. No deprecation mechanism in maven and if this module is used directly downstream (admittedly unlikely here) it would be confusing why the build fails.

It doesn't need to stay where it is though, hence we could put old/empty modules under a subdir.

```
removed/annotation/pom.xml
removed/smsd/pom.xml
```

**Comment by egonw** [comment]
Mmm... what does an empty pom.xml file look like? Just the name, artifactId, etc, but no plugins and no <build>, etc?

**Comment by egonw** [comment]
ping @johnmay, I have restored the annotation pom.xml and rebased this patch on the latest master.

**Comment by johnmay** [comment]
Looks good.

**Pull request merged**
