### PR TITLE
Correct flag for single or double.

### PR DESCRIPTION
**Pull request by johnmay**

### CODE REVIEW

**Comment by egonw** [comment]
This causes regressions on my machine:

Failed tests: 
  CDKAtomTypeMatcherTest.testPyridine_SingleOrDouble:2314->AbstractAtomTypeTest.assertAtomTypes:68->AbstractAtomTypeTest.assertAtomType:140 Incorrect perception for atom 0 expected:<[C.sp2]> but was:<[X]>
  CDKAtomTypeMatcherTest.testPyrrole_SingleOrDouble:2217->AbstractAtomTypeTest.assertAtomTypes:68->AbstractAtomTypeTest.assertAtomType:140 Incorrect perception for atom 0 expected:<[C.sp2]> but was:<[X]>
  CDKAtomTypeMatcherTest.testBenzene_SingleOrDouble:2196->AbstractAtomTypeTest.assertAtomTypes:68->AbstractAtomTypeTest.assertAtomType:140 Incorrect perception for atom 0 expected:<[C.sp2]> but was:<[X]>

**Comment by johnmay** [comment]
Okay will look into it tonight... I'm guessing there was an absolute value specified somewhere.

**Comment by egonw** [comment]
Yeah, I think so too... I have some deadlines to finish today, and did not have time to explore myself yet, I'm afraid...

**Comment by johnmay** [comment]
Double checked and all okay. You need to do a clean install since static variables are inlined by the compiler.

**Comment by egonw** [comment]
Ugh... making it so... hang on...

**Comment by egonw** [comment]
... hang on ... :)

**Comment by egonw** [comment]
Confirmed OK, applied and pushed.

**Pull request closed without merging**
