### PR TITLE
added test case for MDLV2000Reader that gives rise to ArrayIndexOutOf…

### PR DESCRIPTION
**Pull request by uli-f**
…BoundsException; some basic code clean up in MDLV2000ReaderTest

### CODE REVIEW

**Comment by uli-f** [comment]
Please note: build is **expected to fail** as I added a test that will only succeed when implementing a bugfix in `MDLV2000Reader`.

**Comment by johnmay** [comment]
Is it actually a broken molfile? looks like the bond is referencing an atom that doesn't exist?

**Comment by uli-f** [comment]
Agreed. Something is seriously wrong with the molfile.

I'd prefer if I don't end up with a `RuntimeException`, but if that `RuntimeException` could get wrapped in a `CDKException` instead, so that client code doesn't have to catch potentially raised `RuntimeExceptions` when batch-processing larger molecule collections.

But maybe that is just my personal expectations..?

**Comment by uli-f** [comment]
I only saw #950 after pushing my code.

Differences between #950 and my code:
- `MDLV2000Reader` also considers indices below a valid threshold which fixes the test cases I originally wrote up in this PR (and I actually came across in RL)
```
// verify atom indices to avoid an ArrayIndexOutOfBoundsException runtime exception
if (u < 0 || v < 0 || u >= atoms.length || v >= atoms.length) {
      throw new CDKException("Invalid atom index in bond block in line " + lineNum + ": " + line);
}
```
- `MDLV2000ReaderTest` comes with two test cases (atom index in bond block above and below valid range)

**Comment by johnmay** [comment]
I don't think u/v can be negative given we control the parsing of the integer... I would have to check that though.

**Pull request merged**
