### PR TITLE
Patch/maccs166opt

### PR DESCRIPTION
**Pull request by johnmay**
When running the benchmarks for the paper there was a significant improvement (`~10x`) in the MACCS fingerprint speed from 1.4.19. Whilst good a quick look showed lots of optimizations that could be made. Some of these were non-destructive e.g `*~*~*~[S]` starts at all possible atoms and trys to find a path of length 3 to a Sulphur. Whilst `[S]~*~*~*` finds a sulphur and then a path of length 3. Some SMARTS compilers do optimisations like this most don't. This patch optimizes the patterns defined in maccs.txt in two steps, non-changed/changed. The non-changed are safe, the changed are where I think the implementation is wrong/redundant.

As Andrew Dalke points out there is not exact agreement between implementations. 
Changes in the second type fall under whether we match and 8 member (M) ring or an 8M+ ring. The Accelrys doc clearly says, 5M, 6M, 7M, 8M so we match 8M as exactly 8 now. The second type: when the current patterns were written for RDKit they used recursive SMARTS to match alternatives for some bits. This a) slows down the matching, b) adds cases I don't think the MDL impl matched and c) has and odd quirk with counting.

With regards to b), the MACCS key 118 and 147 is ACH2CH2A, the implementation has this as both `
*~[CH2]~[CH2]~*` and `*1~[CH2]~[CH2]~1`. The second one 3 member ring is clearly very rare. If you did want to match you could do: [CH2D2]~[CHD2].

With regards to c) and the above keys `*~[CH2]~[CH2]~*` matches once CHEMBL411976 but `[$(*~[CH2]~[CH2]~*)]` matches twice. Consider the simpler case `OCCO` to see why.

 Once
%5D&zoom=1.3&annotate=none) Twice

Now of course what I think really matter is if the fingerprint performs the same, here are the results on the popular Briem Lessel benchmark:

CDK 1.4.19
```
[duster/benchmark] k=10, measure=Tanimoto, 
[duster/benchmark] Loaded fingerprints in 0s5ms
[duster/benchmark] 5 classes:  ACE (39) TXA2 (48) HMG (109) PAF (132) 5HT3 (47)
[duster/benchmark] Scored fingerprints in 0s45ms
ACE: 68%
TXA2: 61%
HMG: 79%
PAF: 62%
5HT3: 48%
[duster/benchmark] maccs166: 65.7% (63.6% avg-of-avg)
```
CDK 1.5.x
```
[duster/benchmark] k=10, measure=Tanimoto, 
[duster/benchmark] Loaded fingerprints in 0s4ms
[duster/benchmark] 5 classes:  ACE (39) TXA2 (48) HMG (109) PAF (132) 5HT3 (47)
[duster/benchmark] Scored fingerprints in 0s38ms
ACE: 69%
TXA2: 61%
HMG: 80%
PAF: 63%
5HT3: 50%
[duster/benchmark] cdk/macc: 66.5% (64.6% avg-of-avg)
```
CDK 2.0 (this patch)
```
[duster/benchmark] k=10, measure=Tanimoto, 
[duster/benchmark] Loaded fingerprints in 0s4ms
[duster/benchmark] 5 classes:  ACE (39) TXA2 (48) HMG (109) PAF (132) 5HT3 (47)
[duster/benchmark] Scored fingerprints in 0s55ms
ACE: 67%
TXA2: 60%
HMG: 80%
PAF: 63%
5HT3: 52%
[duster/benchmark] maccs166: 66.5% (64.4% avg-of-avg)
```
Some slight change between classes but the same total score.

# Bib
   T.J. O'Donnell, DESIGN and USE of RELATIONAL DATABASES in CHEMISTRY (Appendix) 
   http://accelrys.com/products/pdf/keys-to-keyset-technology.pdf
   http://www.dalkescientific.com/writings/diary/archive/2014/10/17/maccs_key_44.html

### CODE REVIEW

**Comment by johnmay** [comment]
One for @rajarshi, I think he did the original port...

**Comment by johnmay** [comment]
There may be more improvements coming in future to improve the benchmark score slight but I'll wait till after the paper is done to do that.

**Comment by rajarshi** [comment]
Very thorough analysis - I went over most of the modified SMARTS and they look OK to me. I think this is good to go

**Comment by egonw** [comment]
@rajarshi, you don't have rights to push the "Merge pull request" button?

**Comment by egonw** [comment]
Oh, excellent! Good to see you have proper merge rights :)

**Comment by johnmay** [comment]
Thanks for looking over it.

**Pull request merged**
