### PR TITLE
Added element enum to IAtom. Replaced getSymbol usage in HBondDonorCo…

### PR DESCRIPTION
**Pull request by xperrylinn**
First patch for replacing getSymbol by comparing getAtomicNumber against an element enum in IAtom interface.

 Notes:
- set the type of element enum in IAtom to be byte. IntelliJ is letting me know that `public static final` in `public static final byte H = 1;` is redundant for interface fields. I wrote a little python script to write these lines, so please don't hesitate to suggest style changes for the element enum lines.
- getAtomicNumber returns type Integer. I'm using the `==` operator to compare Int and Byte types, which I believe is okay for primitive types.

### CODE REVIEW

**Comment by johnmay** [comment]
👍  Super - great start. 

Comparing int vs byte is okay but I think the JVM actually upcasts the byte first so they could just as well be integer constants. However since it works I think this is good and the class should pack better. I think we should perhaps add a getElement() or getAtomicNum() method that returns the primitive - or update the current one (possible API break). There are cases where atomic number could be null (which would now be a wildcard) where this will cause a NPE.

Any thoughts Egon?

**Comment by egonw** [comment]
> Any thoughts Egon?

The element symbols should be on `IElement` is my first thought

**Comment by egonw** [comment]
Okay, had a bit more time now. Yes, not every `IAtom` is backed by an `IElement`, even though subclassing from it. The situation is quite common in cheminformatics: think R groups, abbreviated groups, wild cards, etc. There is a good bit of cheminformatics history behind this, but also a practical one: we started with Jmol and JChemPaint which both have these use cases.

One idea I experimented at some point was to have `IAtom` not extend `IElement` but have an `IElement` field, which would be null if the atom was not actually an element.

**Comment by johnmay** [comment]
> The element symbols should be on IElement is my first thought

Yeah that does make sense in CDK's class hierarchy actually.

Yes if i were writing it today I would have a much flatter hierarchy (e.g. Atom > ChemObject > CDKObj) rather than (Atom > AtomType > Isotope > Element > ChemObject > CDKObj) since there is no benefit other than semantics.

**Comment by xperrylinn** [comment]
egonw -
> Okay, had a bit more time now. Yes, not every `IAtom` is backed by an `IElement`, even though subclassing from it. 

Understood. I will refactor into the element enum in IElement.

With the element enum placed in IElement, is there a preferred syntax for referencing those values, `IElement.H` or `IAtom.H` or does it matter on context?

johnmay -
> I think we should perhaps add a getElement() or getAtomicNum() method that returns the primitive - or update the current one (possible API break).

For the scope of this PR, should I attempt to accommodate this change or save it for a separate issue?

**Comment by johnmay** [comment]
> For the scope of this PR, should I attempt to accommodate this change or save it for a separate issue?

Separate issue I think, it was more just a thought that popped up, looks great!

**Comment by egonw** [comment]
> With the element enum placed in IElement, is there a preferred syntax for referencing those values, `IElement.H` or `IAtom.H` or does it matter on context?

It's probably just semantics, but my preference would be `IElement.H`.

**Comment by johnmay** [comment]
Looks good

**Pull request merged**
