### PR TITLE
BEAM v1.3.4, Minor change warn/error (when strict) on high order ster…

### PR DESCRIPTION
**Pull request by johnmay**
…eochemistries when the number of explicit neighbours is different to what we expect.

### CODE REVIEW

**Comment by egonw** [comment]
Needs a revision (well, not here :):

```
[ERROR] Failed to execute goal on project cdk-smiles: Could not resolve dependencies for project org.openscience.cdk:cdk-smiles:jar:2.4-SNAPSHOT: The following artifacts could not be resolved: uk.ac.ebi.beam:beam-core:jar:1.3.4, uk.ac.ebi.beam:beam-func:jar:1.3.4: Could not find artifact uk.ac.ebi.beam:beam-core:jar:1.3.4 in ossrh (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
```

**Comment by johnmay** [comment]
Just needed Maven central to sync.

**Comment by johnmay** [comment]
Doh forgot to sign them! Should be a few mins then good.

**Comment by johnmay** [comment]
Grrr getting timeout's now

**Comment by johnmay** [comment]
Looks like issues with load on Sonatype's servers, anyways no rush so will wait a few days and try again to deploy to central.

**Comment by johnmay** [comment]
Should be good now, just triggered rebuild

**Comment by johnmay** [comment]
Hurray for new Travis CI queue :(

**Pull request merged**
