### PR TITLE
Add/constant fields

### PR DESCRIPTION
**Pull request by michaelwenk**
Some constant fields in CDKCONSTANTS  for NMR spectrum types were added.

### CODE REVIEW

**Comment by johnmay** [comment]
Where does ``casekit.NMR.model.Spectrum#specType`` reside for the doc?

**Comment by michaelwenk** [comment]
Hi,
these are links to another project of me.

**Comment by johnmay** [comment]
If possible put in the HTML links, for example:

```
@see <a href="externaldoc.com/api/page.html">casekit.NMR.model.Spectrum#specType</a>
```

**Comment by michaelwenk** [comment]
Dear John,

I removed this @see links because I don't have such Javadoc page yet.

Best regards,
Michael

**Comment by johnmay** [comment]
Thanks, could you squish these down and do a force push. Just keeps things nice and tidy. 

Step 1. $ git rebase -i HEAD~4
Step 2. Edit the display such that only the first commit is keep but the other 3 are marked as 'f' (fixup)
Step 3. Check everything looks okay in the history and force push

**Pull request merged**
