### PR TITLE
Integrating MAYGEN project to structgen package

### PR DESCRIPTION
**Pull request by javadev**

### CODE REVIEW

**Comment by johnmay** [comment]
Sorry I have this on the branch locally, the dependance on commons-cli needs to go - also (I have made that change). I also suspect cdk-group isn't needed but need to dig deeper. If you split out the SDF change to a separate PR I can pull that in right away.

**Comment by javadev** [comment]
@johnmay here your are https://github.com/cdk/cdk/pull/802

**Comment by javadev** [comment]
> Sorry I have this on the branch locally, the dependance on commons-cli needs to go - also (I have made that change). I also suspect cdk-group isn't needed but need to dig deeper. If you split out the SDF change to a separate PR I can pull that in right away.

commons-cli dependency was excluded from the pull request. cdk-group is used in class Maygen.

**Comment by johnmay** [comment]
This fix isn't quite right since the fields are private there is no way to configure it. Basically to go in to CDK it needs to have an actually API and not some opaque executable invocation. I also really don't like it handling the IO writing, makes sense for a command line - not for a modular API.

 I just wanted to start working on this now but got sidetracked by stupid xerces issues.

**Comment by javadev** [comment]
It may be added to cdk and improved latter. I think real customer will use a command line library.

**Comment by johnmay** [comment]
But the point is we don't currently have any command line :-). So it should just be it's own project.

**Comment by javadev** [comment]
I hope it will merged soon.

**Comment by MehmetAzizYirik** [comment]
> This fix isn't quite right since the fields are private there is no way to configure it. Basically to go in to CDK it needs to have an actually API and not some opaque executable invocation. I also really don't like it handling the IO writing, makes sense for a command line - not for a modular API.
> 
> I just wanted to start working on this now but got sidetracked by stupid xerces issues.

@johnmay we already had the initial pull request and we formatted that as Egon's recommended. Just to share my thoughts: we can re-open the initial pull request and close this one. Then doing the changes on that clean version. CDK has its own format and that is why I did not wanna do any changes after sharing with you. Rather than doing these changes and asking whether it is correct or not for CDK, with your guidance we can work on the clean version.

**Comment by egonw** [comment]
> But the point is we don't currently have any command line :-). So it should just be it's own project.

Some many moons ago "we" made the wise decision to not have command line utilities in the main library and removed the CLI wrappers we had at the time (yes, in a long past we did have CLI tools).

We should start a project to have these CLI tools again. Besides the MAYGEN CLI tool, we'll have a (SDF, SMILES) file validator, our own `babel`, etc.

**Comment by johnmay** [comment]
Now #811

**Pull request closed without merging**
