### PR TITLE
Patch/yaochunwei patches

### PR DESCRIPTION
**Pull request by johnmay**

### CODE REVIEW

**Comment by johnmay** [comment]
Updated - had manually apply some bits. Also deprecated DeAromTool.

**Comment by egonw** [comment]
@johnmay, I've done a clean install, but getting this error:

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:testCompile (default-testCompile) on project cdk-smsd: Compilation failure: Compilation failure:
    [ERROR] /home/egonw/var/Projects/SourceForge/git/cdk/tool/smsd/src/test/java/org/openscience/cdk/smsd/algorithm/rgraph/CDKRMapHandlerTest.java:[70,22] error: non-static method setSource(IAtomContainer) cannot be referenced from a static context

And it seems this class is not changed in any of the commits...

**Comment by johnmay** [comment]
Ah but the class it was using did. My bad patching now.

**Comment by johnmay** [comment]
Hmm not sure why extra patch isn't showing up.

**Comment by egonw** [comment]
No worries; I found it...

**Comment by egonw** [comment]
Applied and pushed.

**Pull request closed without merging**
