### PR TITLE
Added auto-generated OSGi metadata

### PR DESCRIPTION
**Pull request by Mailaender**
I want to get rid of [net.openchrom.thirdpartylibraries.cdk](https://github.com/OpenChrom/openchrom3rdpl/tree/develop/openchrom/plugins/net.openchrom.thirdpartylibraries.cdk) and this seems to be a requirement.

### CODE REVIEW

**Comment by johnmay** [comment]
More info needed. What are you doing and why?

By get rid of you means push the osgi in the main repo?


I’ve never seen a strong argument for OSGI but providing the build and deployment (central upload) size doesn’t change I have no strong objection.

**Comment by Mailaender** [comment]
Yes, I can then fetch CDK via Maven (instead of rebundling .jars) and integrate it into the target platform. Compare the MANIFEST.MF before and after to see what this actually does.

**Comment by egonw** [comment]
OSGi-bundles for the CDK modules would help me too. E.g. Cytoscape and PathVisio have plugins that use the CDK and need OSGi bundles.

I am not Maven/OSGi expert (never had enough time to understand all the complexities, tho I got the basics). Are there any downsides of marking each module a "bundle"?

**Comment by Mailaender** [comment]
A bundle is a jar with OSGi metadata according to https://stackoverflow.com/a/20260459 so I hope this does not change any existing build workflows.

**Comment by johnmay** [comment]
Done some tests locally and this seems to double the installation size. It's already much bigger than I would like to some recent third-party updates (#911) and I'm hesitant to double that.

```
find . -name '*.jar' | xargs du -sch | sort -h
```
...
176K  ./descriptor/fingerprint/target/cdk-fingerprint-2.9-SNAPSHOT.jar
192K  ./display/renderbasic/target/cdk-renderbasic-2.9-SNAPSHOT.jar
212K  ./misc/extra/target/cdk-extra-2.9-SNAPSHOT.jar
240K  ./descriptor/qsarmolecular/target/cdk-qsarmolecular-2.9-SNAPSHOT.jar
244K  ./tool/sdg/target/cdk-sdg-2.9-SNAPSHOT.jar
308K  ./base/core/target/cdk-core-2.9-SNAPSHOT.jar
324K  ./base/standard/target/cdk-standard-2.9-SNAPSHOT.jar
440K  ./storage/io/target/cdk-io-2.9-SNAPSHOT.jar
560K  ./storage/pdb/target/cdk-pdb-2.9-SNAPSHOT.jar
600K  ./legacy/target/cdk-legacy-2.9-SNAPSHOT.jar
2.2M  ./tool/builder3d/target/cdk-builder3d-2.9-SNAPSHOT.jar
 46M  ./bundle/target/cdk-2.9-SNAPSHOT.jar
 54M  total
```

after:

```
...
2.2M  ./storage/pdb/target/cdk-pdb-2.9-SNAPSHOT.jar
2.3M  ./app/depict/target/cdk-depict-2.9-SNAPSHOT.jar
2.3M  ./storage/pdbcml/target/cdk-pdbcml-2.9-SNAPSHOT.jar
2.9M  ./legacy/target/cdk-legacy-2.9-SNAPSHOT.jar
4.7M  ./tool/builder3d/target/cdk-builder3d-2.9-SNAPSHOT.jar
 45M  ./bundle/target/cdk-2.9-SNAPSHOT.jar
106M  total
```

It looks like what it does is pull in all the dependant files of the project.

Before:
```
[john@sentinel:cdk]% tar tvf ./storage/pdb/target/cdk-pdb-2.9-SNAPSHOT.jar | wc -l
      25
```
After:
```
[john@sentinel:cdk]% tar tvf ./storage/pdb/target/cdk-pdb-2.9-SNAPSHOT.jar | wc -l
     810
```

This might be better once we are more modularised move to Java modules but for now I think this is possible a no go unfortunately.

**Comment by Mailaender** [comment]
I see. Modified it according to https://bnd.bndtools.org/tools/felix-maven.html so that the packaging type stays `.jar` using the “Maven first” approach.

**Comment by egonw** [comment]
> Done some tests locally and this seems to double the installation size.

Okay, that's not what I had in mind or expected. That does not make sense to me either. As far as I know it should only update the `MANIFEST.MF` file. I cannot imagine a >1MB manifest file. The increase in number of lines is also weird.

Are we sure this is not an interaction effect and that it makes every module a "with dependencies" now?

**Comment by johnmay** [comment]
> I see. Modified it according to https://bnd.bndtools.org/tools/felix-maven.html so that the packaging type stays `.jar` using the “Maven first” approach.

Much better, thanks just test and all looks ok.

**Comment by johnmay** [comment]
Note to future self.

The build was made a little slower (+18% user time ~49s => ~59s, real time ~19s => ~20.4s M1 Pro). OK but careful of "death by a thousand paper cuts". Likely improved by less modules.

**Comment by egonw** [comment]
An alternative is to have the extra manifest information in a separate file (if not mistaken), and have the plugin use that to create the OSGi bundle. Less build time, more admin.

**Pull request merged**
