### PR TITLE
Improved angle snapping replacing countAlignedBonds with a more gener…

### PR DESCRIPTION
**Pull request by johnmay**
…al histogram method. First a histogram is calculated for angles wrapper 0..60, we then use this to click into place and then rotate at 60 degree increments.

image image

### CODE REVIEW

**Comment by johnmay** [comment]
Before and after shots if that wasn't obvious...

**Comment by johnmay** [comment]
Hmm... messes up pyrrole though... can't have that

image

**Comment by johnmay** [comment]
Okay should be good to go now...
image
Will align if there is >50% of bonds that could be aligned
image

**Comment by egonw** [comment]
PS, if we have compounds like lipids with one or more long tails, or something like [caldarchaeol](https://web.archive.org/web/20080216125040/http://www.uoeh-u.ac.jp/kouza/ikagaku/research_e.html), any change we can trigger that it puts the tails nicely aligned next to each other?

**Comment by johnmay** [comment]
Would be best to do as a bit of custom preprocessing... I was thinking of
this for Peptide/Sugars for example we could generate chair/haworth
depictions which are subjectively nicer for sugars.

**Pull request merged**
