### PR TITLE
Implementation of the counting MACCS fingerprints

### PR DESCRIPTION
**Pull request by bachi55**
Hei, 

I made an implementation of the counting version of the MACCS fingerprints. Not all fingerprint definitions have a counting counterpart so I made the following assumptions (for the translation from binary --> counting definition):
1. Binary FPs that put molecules into a certain group, e.g. [Ac,Th,Pa,...] 0 | Actinides.
==> Stay with the binary value for the groups.
2. Binary FPs that looking for one, two, etc occurrences:
==> Merge those fingerprints to a simple count of the corresponding structure.
3. Fragments
==> Number of fragments is counted
4. Remaining definitions, e.g. Rings, ...
==> Simply count number of occurrence.

Best regards

### CODE REVIEW

**Comment by johnmay** [comment]
Why do you want/need this? MACCS is also known to be a poor performing fingerprint.

If you really want to do this, I think the best option would be to create a new class. Your changes mean this is no longer a MACCS fingerprint as you've changed the patterns, counting just doesn't really make sense for MACCS.

**Comment by johnmay** [comment]
In fact, I think the best option is to update the more generic "SubstructureFingerprint" with a count method. You can then simply pass in the MACCS patterns, don't get the ring optimisations but much cleaner.

**Comment by bachi55** [comment]
Counting fingerprints can be useful in the context of chromatographic retention prediction for molecules. When working with counting fingerprints, I started with MACCS, as those are easy to interpret regarding what "count" actually means.

I will have a look onto your suggestion to extend the "SubstructureFingerprint" class.

**Comment by johnmay** [comment]
It's difficult because MACCS does mean something specific, it doesn't have a count implementation because the definitions simply don't translate. Some of the MACCS bits for example are specific to finding a pattern multiple times.

Note you can map the Circular fingerprint bits back to the molecule part with the [``SmartsFragmentExtractor``](http://cdk.github.io/cdk/latest/docs/api/index.html?org/openscience/cdk/smarts/SmartsFragmentExtractor.html).

**Comment by bachi55** [comment]
What do you think about the following solution: As you suggested I would extend the ```SubstructureFingerprinter``` class so that it can provide the counts for the set of provided patterns. 

For the MACCS fingerprint definitions: I would create a new list of patterns ...

- Patterns that clearly can be **counted**, _e.g. 6-Ring, [O=C], etc_. 
- Patterns / keys that are like _"is there at least 1 of this and that", "are there at least 2 ..." etc._ would be **merged into one single count**. 
- Patterns that clearly correspond to binary properties, _e.g. actinide group ([Ac,Th,Pa, ...]), isotope, etc._, would be **removed**. 

This would not be counting MACCS fingerprints, but a new list of patterns derived from the MACCS definitions.

**Comment by johnmay** [comment]
Yep that sounds good, I would add:

 - "extend" by updating ``SubstructureFingerprinter.getCountFp`` method
 - I can't remember how the current patterns are defined, maybe have a static array on the ``SubsturtureFingerprinter``
```
SubsturtureFingerprinter sfp = new SubsturtureFingerprinter(SubsturtureFingerprinter.MODIFIED_MACCS166);
``` 
 - use the ``Pattern.matchAll().countUnique()`` directly the additional utility method is just an extra API point - the small the API the better and CDK's is already massive! [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

**Comment by johnmay** [comment]
Thanks will have a look as soon as possible but first glance looks good.

A quick SMARTS tips, ``:`` implies ``@`` so ``:@`` is the same as ``:``. Same with ``a`` and ``R``, therefore you can simplify your 6M aromatic ring pattern, not going to be a huge win but useful to know:

```
[aR]:@1:@a:@a:@a:@a:@a1
a:1:a:a:a:a:a1 (optimal)
```

Useful slides if you're interested in SMARTS - http://www.daylight.com/meetings/summerschool99/course/basics/ref/sayle/slides.html

John

**Comment by bachi55** [comment]
Hei John,

thank you for your tip. I will upgrade the SMARTS lists.

Another thing: At the moment I implement the counting of the matches for a particular SMARTS pattern. There is something I am not sure about: **Is the function:**

```java
SMARTSQueryTool.getUniqueMatchingAtoms().length()
```
(Assuming that the class ```SMARTSQueryTool``` uses the Ullmann-model in the ```matches()``` function.)
**equivalent to** 
```java
Ullmann.findSubstructure(query).matchAll(atomContainer).uniqueAtoms().count()
```
**?**

Best regards,

Eric

**Comment by bachi55** [comment]
Currently the ```SubstructureFingerprinter```-class uses ```SMARTSQueryTool```, which internally uses Ullmann. Should I change this at the same time, so that directly the pattern interface is used? 

Eric

**Comment by johnmay** [comment]
Don't worry about it for this patch. But feel free to submit another, in fact the entire SubstructureQueryTool should be deprecated moved to the cdk-legacy package.

**Comment by johnmay** [comment]
Looks good, is ``SubsturtureFingerprinter`` missing the ``getCountFp`` implementation? Difficult to tell via GitHub?

Otherwise all looks okay, I might change the SubstructureFingerprint constructor API slightly to avoid adding the new ENUM (e.g. just a list of SMARTS) but I can do that.

**Comment by johnmay** [comment]
Also I'll need to cherry pick the last four commits. So will do that manually.

**Comment by bachi55** [comment]
Hei John,

yeah actually my last changes, e.g. the getCountFp code is not committed yet. I could only sporadically add the code and also wanted to know, what to do with the ```SMARTSQueryTool```. 

As this is my first pull request, I also did not know, that you see the related commits from my forked repository, so that I created "noise" before the work actually got ready. 

I am working today on it. Can you open the request again, or is this even needed?

Best regards,

Eric

**Comment by bachi55** [comment]
I finished the implementation of the counting ```SubstructureFingerprinter```. I added two _new_ substructure definitions (cdk/descriptor/fingerprint/src/main/resources/org/openscience/cdk/fingerprint/data):
* ```SMARTS_countable_MACCS_keys.txt```: Countable MACCS keys
* ```SMARTS_binary_MACCS_keys.txt```: Binary MACCS keys (added for convince)

I also reverted the changes made to the ```MACCSFingerprinter```-class and removed the wrapper function ```countUniqueMatches()```.

-Eric

**Comment by bachi55** [comment]
> Otherwise  all looks okay, I might change the SubstructureFingerprint constructor  API slightly to avoid adding the new ENUM (e.g. just a list of SMARTS)  but I can do that.

Can I help somehow with this as well? I have seen that the ```KlekotaRothFingerprinter``` simply extends the ```SubstructuresFingerprinter```-class and inputs the SMARTS "directly". However, lets say a ```CountingMACCSFingerprinter```-subclass seems to me a bit confusion, as there is already a specific MACCS fps class. 

What do you think about adding a features that allows to pass filename of a SMARTS list to the ```SubstructureFingeprinter```? This would probably also simplify the integration of the results of this merge-request into [rcdk](https://github.com/rajarshi/cdkr).  (Which is something I have in mind.)

-Eric

**Comment by johnmay** [comment]
I'll take it from here and get this integrated today, thanks. Quick tip for future is ``git rebase -i`` is really useful if you don't know it. You can squish (collapse multiple changes in to one), reword (change commit messages), and even remove commits.

**Comment by johnmay** [comment]
Okay cherry picked in the commits there were needed then did a clean up one.

**Comment by johnmay** [comment]
Here is the cleanup commit: https://github.com/cdk/cdk/commit/0aa59e3d0a0edc9b03d66f8aeda60aa2ef4574c5

**Comment by bachi55** [comment]
Thank you for your help and advices!

**Pull request closed without merging**
