### PR TITLE
Modified WeightDescriptor calculate method to return natural mass. 

### PR DESCRIPTION
**Pull request by studur**
Minor refactoring.
Updated unit tests in WeightDescriptorTests

### CODE REVIEW

**Comment by studur** [comment]
@egonw Hello, could I have a code review on this please ? Thank you !

**Comment by studur** [comment]
PR to patch https://github.com/cdk/cdk/issues/510

**Comment by johnmay** [comment]
Better but still not MW, this is now calculating Avg Wt. Although synonymous in the majority of cases the difference comes when one atom has an isotope specified or not. 

The conclusion from previous threads was we would make the names more intuitive:

MolWeight -> AtomContainerManipulator.getMolecularWeight  (avg if unspecified, exact if specified)
AvgWeight -> AtomContainerManipulator.getNaturalMass
MonWeight -> AtomContainerManipulator.getExactMass
AbuWeight (Most Abundant) -> To be written

**Comment by johnmay** [comment]
So there will be a single function.

```
AtomContainerManipulator.getMass(mol, MolWeight));
AtomContainerManipulator.getMass(mol, MolWeight));
AtomContainerManipulator.getMass(mol, MolWeight));
```

**Comment by johnmay** [comment]
In principle I think the patch is fine though I need to look at what was intended in the first place.

**Comment by studur** [comment]
Thank you for the comments.

**Pull request merged**
