### PR TITLE
added test case for initial cycles oom

### PR DESCRIPTION
**Pull request by uli-f**
test case for #976

### CODE REVIEW

**Comment by johnmay** [comment]
Ah it's another bug when trying to actually generate them, I'll try and find time to take a look. Thanks.

**Comment by johnmay** [comment]
Hi @uli-f,

Just letting you know this, and the RDF, and the SMIRKS bits are on my radar. Doing a 2.9 release but I will try and get round to getting these bits fixed/merged in soon. Sorry it's taken so long, just too much to do :-)

**Comment by uli-f** [comment]
> Hi @uli-f,
> 
> Just letting you know this, and the RDF, and the SMIRKS bits are on my radar. Doing a 2.9 release but I will try and get round to getting these bits fixed/merged in soon. Sorry it's taken so long, just too much to do :-)

Thanks @johnmay, that is good news! I very much appreciate all the work you put into CDK.

With the _RDF bits_ I assume you are referring to #942 ? If so please let me know if there is anything I can do on my side to get this merged. It is a bit half-baked because I wanted to get some feedback before continuing...

**Comment by johnmay** [comment]
Need to modify the test to check for the exception now.

**Comment by egonw** [comment]
> Need to modify the test to check for the exception now.

yes, I just saw that:

```shell
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   AromaticityTest.outOfMemoryExceptionInitialCycles:178 » Intractable Too many relevant cycles cycles! max=512000 was=16777240. Increase this limit with System property -Dcdk.maxRelevantCycles=<num>
[INFO] 
[ERROR] Tests run: 1005, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by egonw** [comment]
@johnmay, are you fixing this? or shall I?

**Comment by johnmay** [comment]
Well on this branch needs to be @uli-f - but we can send a PR to the PR if that makes sense. 

Just needs an ``Assertions.assertThrows()``

**Comment by egonw** [comment]
> but we can send a PR to the PR if that makes sense.

Ah, we don't have that option enabled? Let me check ...

**Comment by egonw** [comment]
> Ah, we don't have that option enabled? Let me check ...

@johnmay, yes, it was enabled. I have just made the extra patch.

**Comment by johnmay** [comment]
Missing an import I think, how did you do the PR and have it appear automatically? 

I needed to do that the Ertl Functional Group stuff

**Comment by johnmay** [comment]
Oh you just push to their branch, odd.

**Comment by johnmay** [comment]
Nope I don't understand,

```
 ! [remote rejected]       uli-f-oom_initial_cycles -> uli-f-oom_initial_cycles (permission denied)
error: failed to push some refs to 'github.com:uli-f/cdk.git'
```

**Comment by johnmay** [comment]
Now I'm more confused how you did it @egonw. I followed this (https://tighten.com/insights/adding-commits-to-a-pull-request/) but had to rebase hence they are all in here now.

I will close and just do this seperately.

**Comment by egonw** [comment]
> Now I'm more confused how you did it @egonw.

This is what I did (actually not in the way I hoped, but not sure if that feature still exists: in the past you could propose edits to patches):

1. the author of the PR has to have had enabled the option (checkbox in the "create PR" page). You then should see this (when the PR is still open; that's why I just had to reopen it again):

image

2. view the full file via the three dots in the top right:

image

3. check if the right branch version

4. then use the web UI to "edit" the file and push. because of the option in step 1, maintainers (you, me) should be able to push

**Comment by johnmay** [comment]
Ah OK, thanks. I did mange to push it as you saw but think I rebased wrongly. No worries.

**Pull request closed without merging**
