### PR TITLE
Locate fix

### PR DESCRIPTION
**Pull request by markussitzmann**
In addition to the fix for https://github.com/cdk/cdk/issues/579 I found two further spot where the addition of DecimalFormatSymbols helps on my system (one is related to https://github.com/cdk/cdk/issues/507)

### CODE REVIEW

**Comment by johnmay** [comment]
The InChI one is not correct as InChI library is also local specific. Worse it use a different locale setting to Java.

**Comment by egonw** [comment]
The one in the InChI code is special: the InChI library uses the local (wrong) notation on the command line for some of the parameters. That one should not change, as John said.

@markussitzmann, can you plz update the patch? (Or shall we go ahead with the good bits?)

**Comment by markussitzmann** [comment]
I'll change it.

**Comment by johnmay** [comment]
Thanks

**Pull request merged**
