### PR TITLE
added maven plugin to generate checksum for bundle uber-jar

### PR DESCRIPTION
**Pull request by uli-f**

### CODE REVIEW

**Comment by johnmay** [comment]
Looks good, what does it generate? An extra file cdk.jar.sha256 for example?

**Comment by uli-f** [comment]
> Looks good, what does it generate? An extra file cdk.jar.sha256 for example?

Yes, for each hashing algorithm it writes a file to `bundle/target` that starts with the filename of the uber-jar and adds the name of the hashing algorithm:

```
cdk-bundle-2.9-SNAPSHOT.jar.sha256
cdk-bundle-2.9-SNAPSHOT.jar.sha512
cdk-bundle-2.9-SNAPSHOT.jar.sha3512
```

The hashing algorithms and the location and name of the output file is configurable.

**Comment by egonw** [comment]
When merged, give me a ping. I will push a SNAPSHOT deploy to Maven Central and see if that works fine. Not sure what it does, but with a bit of luck, the checksums get moved there too? We'll see.

**Comment by uli-f** [comment]
> When merged, give me a ping. I will push a SNAPSHOT deploy to Maven Central and see if that works fine. Not sure what it does, but with a bit of luck, the checksums get moved there too? We'll see.

If artifacts get deployed to a repository via maven deploy they already sit right next to checksum files in the repo:
https://repo1.maven.org/maven2/org/openscience/cdk/cdk-base/2.8/
When pulling in dependencies from a maven repo, checksums of artifacts are verified.

The maven plugin I added produces checksum files and stores them _locally_. The use case here is to upload them to GitHub when a release is made to be able to manually verify the uber-jar `cdk-bundle`.

**Comment by johnmay** [comment]
Thanks, will try and find time soon to get the other bits reviewed/merged. In the end I had no free time over Christmas to look at them - Sorry.

**Comment by uli-f** [comment]
> Thanks, will try and find time soon to get the other bits reviewed/merged. In the end I had no free time over Christmas to look at them - Sorry.

No worries. Thanks for all the time you are putting in 🙌🏼

**Pull request merged**
