### PR TITLE
SMARTS bits

### PR DESCRIPTION
**Pull request by johnmay**
Been working on something fun when I was on Holiday which made me realise some updates to the SMARTS/Query APIs would be needed.

### CODE REVIEW

**Comment by johnmay** [comment]
Odd passes OK locally

**Comment by johnmay** [comment]
Perhaps need to think what is the most sensible default for unique atoms vs unique atom sets.

**Comment by johnmay** [comment]
> Odd passes OK locally

They didn't :-)

**Comment by egonw** [comment]
Looks good to me.

**Comment by johnmay** [comment]
Testing other toolkits I thin I will reverse the Unique filtering naming. Most do consider (0,1,2), (0,1,3) and (2,1,3) to be unique.

**Pull request merged**
