### PR TITLE
Fix issue with hose code nesting

### PR DESCRIPTION
**Pull request by johnmay**
Fixes an issue with Hose Code nesting via #588.
We can actually see from another test that the output was wrong since it didn't make sense.

example:

image
image
image

So
```
C,
C,C,C
CC,CC,CO
```

but we had

```
C,
C,C,C
CC,CC,C,O
```

It's logically inconsistent to have 4 in the second sphere and 3 in the first.

### CODE REVIEW

**Comment by johnmay** [comment]
I may still rewrite this code as it appears to be doing a lot more than it needs to. In my mind it should just be a simple breath-first order traversal using a comparator but it's going around the houses making temporary objects and comparison keys (maybe this was pre-generics).

**Comment by johnmay** [comment]
``Cl-1;C(*C*C/H,H,*C,*C/H,H,*C,*&)H*&//////  753.1`` (was)
vs
``Cl-1;C(*C*C/H*C,H*C/H*C,H*&)H*&////// 753.1`` (now)

Again completely wrong since ``*C*C/H,H,*C,*C`` doesn't make sense. Now do I write a hose code validator...

**Comment by egonw** [comment]
@steinbeck, can you have a look at this? I know the idea, but never actively used HOSE codes... or know someone who is willing to check this patch?

**Comment by johnmay** [comment]
One option to have both options is we can have an option to generate old (incorrect) CDK hose codes and the fixed ones.  There is a strong overlap between them so mostly they are compatible. The two QSAR descriptors are most problematic since they use many layers.

Then existing usages can use the old ones if needed. The tricky part here is a lot of the usages are very old - circa 2004 - and probably bit-rotted quite heavily all-ready. In which case I would favour just deprecating and moving things to cdk-legacy.

**Comment by egonw** [comment]
Maybe not a bad idea, but ideally the descriptors are recalculated indeed. We have a `cdk.cite` javadoc tag which was meant to allow proper documents, but we were all learning, I guess. Which two were these again? Maybe from Miquel?

**Comment by johnmay** [comment]
Yep - there isn't much info "Weka(J48)" (a classifier) and "NIST"

**Comment by egonw** [comment]
@johnmay, this PR is now conflicting too :/

**Comment by johnmay** [comment]
Yes need to rebase - it's fine need some more thought anyways

**Comment by egonw** [comment]
@johnmay, got an update?

**Comment by javadev** [comment]
This branch has conflicts that must be resolved

**Comment by johnmay** [comment]
Marked as draft, these changes would break other parts (models trained on the wrong values) so it is difficult to merge in for now.

**Comment by johnmay** [comment]
A new constructor parameter (flags) has been added, all existing usages use new HOSECodeGen(LEGACY_MODE); to keep compatible behaviour.

**Comment by johnmay** [comment]
I'm OK with the 5 code smells.

**Review by egonw — APPROVED** [review]
Looks good to me. With this low level changes, the impact can be big, and I am not sure if all use cases still work, but at least some are that have tests too, and since there are no regressions, I am happy to apply.

**Pull request merged**
