### PR TITLE
Depend on a newer Xerces version

### PR DESCRIPTION
**Pull request by egonw**

### CODE REVIEW

**Comment by egonw** [comment]
Mmm... it failed on the following code (which I did not get here... maybe bc I forgot to compile with Java 8):

```
java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
	at org.openscience.cdk.normalize.NormalizerTest.testNormalize(NormalizerTest.java:49)
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal
	at org.openscience.cdk.normalize.NormalizerTest.testNormalize(NormalizerTest.java:49)
```

**Comment by egonw** [comment]
Confirmed. Does not work with Java 8 :(

**Comment by johnmay** [comment]
Yes I had the same issue when trying to sort out the transitive dependencies. :)

**Comment by javadev** [comment]
We meed one mire dependency

```
<dependency>
    <groupId>xml-apis</groupId>
    <artifactId>xml-apis</artifactId>
    <version>1.4.01</version>
</dependency>
```

**Comment by johnmay** [comment]
Fixed by #806

**Pull request closed without merging**
