### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by egonw**

### CODE REVIEW

**Comment by johnmay** [comment]
Can't update Mockito as needs a newer JVM

**Comment by egonw** [comment]
> Can't update Mockito as needs a newer JVM

Oh, not again. Sorry. I thought I was compiling with Java8 :( 

And forgot to wait for the checks here.

**Comment by egonw** [comment]
@johnmay, new try. Not sure about the sonarcloud fail. I have that for my other PR of this weekend too. I see this error:

```
Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:5.0.0.4389:sonar (default-cli) on project cdk: Error status returned by url [https://api.sonarcloud.io/analysis/jres?os=linux&arch=x86_64]: 401 -> [Help 1]
```

But not sure what to do with that.

**Comment by johnmay** [comment]
FYI the mesg is just {"Message":"User is not authorized to access this resource with an explicit deny"}

**Comment by johnmay** [comment]
It won't run on forks.

**Pull request merged**
