### PR TITLE
Stable build

### PR DESCRIPTION
**Pull request by johnmay**
Fix the Travis build - sorry should have been on top of these.

### CODE REVIEW

**Comment by johnmay** [comment]
Ek that Guava update broke a lot. It really erks me when the Maven/IDE caches build as I ran a build before I uploaded and looked fine.

**Comment by johnmay** [comment]
Wait hang-on I just pushed a snapshot build to OSSRH... so why is it failing...

**Comment by johnmay** [comment]
Ah nvm, you merged before the guava bit... no worries. Will add to a different PR - also looks like good time to upgrade to Java 1.8

**Comment by egonw** [comment]
Sorry, I had not noticed it gave trouble :(

**Pull request merged**
