### PR TITLE
More consistent MOLfile/SDfile property handling.

### LINKED ISSUE #971: differences in processing V2000/V3000 tag data
I'm finishing up support for using CDK to read V3000 SDF records in chemfp, and found a problem during testing.

Everything is fine when I use IteratingSDFReader to read a file. I am able to get the molecule and its associated tag data with both V2000 and V3000 records. 

I have a problem when reading a single record, where the cdk.io.MDLV2000Reader().read() parses the tag data while the cdk.io.MDLV3000Reader().read() does not.

When I parse a single SDF record, I figure out if it's V2000 or V3000 and dispatch to the appropriate MDL Reader. This replicates what IteratingSDFReader does (see  #952). I decided to use this approach as I find it gives better error reporting than IteratingSDFReader - the latter catches and logs errors, because it's designed to skip records it can't handle rather than raise an exception (see  #951)

I discovered that while MDLV2000Reader parses the tag data, MDLV3000Reader does not. More specifically, MDLV2000Reader.readAtomContainer has readNonStructuralData() to read the tag data:
```
            // read potential SD file data between M  END and $$$$
            readNonStructuralData(input, outputContainer);
```
and that in turn sets `container.setProperty(header, data.toString())`.

On the other hand, MDLV3000Reader does not parse the tag data, which you can verify by failing to find the relevant setProperty() call.

This is not an issue *when using IteratingSDFReader* because the iterating reader will only have the MDL reader process a record up to the M_END (ie, MDLV2000Reader will never call readNonStructuralData), then the iterating reader will parse the tag data itself, using readDataBlockInto():
```
                if (currentLine.startsWith(M_END)) {
                     ...
                        molecule = reader.read(builder.newAtomContainer());
                      ...
                    if (molecule != null) {
                        readDataBlockInto(molecule);
```

(Also, it uses a  different algorithm; MDLV2000Reader requires the SDF end with "$$$$" exactly while IteratingSDFReader says the line only needs to start with "$$$$".)

My work-around is to parse the tag data myself, if it's a V3000 record, and set the corresponding properties.

### PR DESCRIPTION
**Pull request by johnmay**
Fixes #971.

Also removes the property reading from the Iterating Reader since the base readers now do it. We can do a little better with the IteratingSDFReader loop - will try and add that tonight.

### CODE REVIEW

**Comment by johnmay** [comment]
OK should be good now, hold off merging right away I might add in the property consistent the writers as well.

**Comment by johnmay** [comment]
Yep will remind me to finish it! Doing an InChI meeting ATM but will have time later in week

**Comment by johnmay** [comment]
There is also a annoyance the SDFWriter can accept a set of properties to write... so probably need a ``StringListIOSetting`` or similar.

**Comment by johnmay** [comment]
I might just make that a API only setting for now

**Comment by johnmay** [comment]
OK I think this is good, I will check the code smells when they come in though. Ultimately I need to get working on the V2000/V3000 merging

**Comment by egonw** [comment]
@johnmay, shall we merge this one in?

**Comment by johnmay** [comment]
On holiday at the moment so will check when I am back on Wednesday/Thursday

**Comment by johnmay** [comment]
Good to go!

**Comment by egonw** [comment]
Locally resolved the conflicted and merged.

**Pull request closed without merging**
