### PR TITLE
Resolved Sonar issue with addAll in unmodifiable set

### PR DESCRIPTION
**Pull request by javadev**

### CODE REVIEW

**Comment by egonw** [comment]
I am not sure I can oversee the implications.

@javadev, do you have a situation where the previous code fails that we can use for a (unit) test?

**Comment by javadev** [comment]
> I am not sure I can oversee the implications.
> 
> @javadev, do you have a situation where the previous code fails that we can use for a (unit) test?

If an exception for `addAll` is the expected behavior, we can leave this code unchanged. By the way, this class is deprecated.

**Comment by johnmay** [comment]
I don’t think sonar is quite correct here, the addAll is guarded by a minSize condition which is Interger max - you would never be able to find a cycle that big :)

**Comment by johnmay** [comment]
A technically better condition would be minSize = num atoms in mol + 1

**Comment by johnmay** [comment]
I’ve merged as it’s technically fine and Java does optimise empty collections.

I do tend to find such cases a waste of energy. In future please show the exception being triggered - which in this case would be impossible (you would run out of memory if a molecule had 2 billion atoms)

**Pull request merged**
