### PR TITLE
Fix/pmd warnings

### PR DESCRIPTION
**Pull request by egonw**
John, I had planned to do some more, but was distracted by BridgeDbR download stats...

PMD warning fixes...

### CODE REVIEW

**Comment by johnmay** [comment]
Looks good but travis build problems in RingSetManipulatorTest

**Comment by egonw** [comment]
John, indeed... I will look into that!

**Comment by egonw** [comment]
I think it's the removal of an import line... I was already wondering about that when I did that, because it showed no compile errors, and thought I had already remove all unused imports... seems something fishy with my Eclipse installation... I will remove that last commit.

**Comment by egonw** [comment]
@johnmay ping... troublesome patch removed.

**Pull request merged**
