### PR TITLE
Upgrade Beam version, new features include optimised and improved bon…

### PR DESCRIPTION
**Pull request by johnmay**
…d placement (kekulisation,double-bond direction) algorithms and title processing. Titles are now conveniently parsed in the SmilesParser.

### CODE REVIEW

**Comment by johnmay** [comment]
I think it's waiting for Beam 0.9 in central... should be there soon.

**Comment by egonw** [comment]
OK, I'll wait for that...

**Comment by johnmay** [comment]
Yeah just seen my signed files are missing will debug tonight.

**Comment by johnmay** [comment]
Okay released now - https://oss.sonatype.org/content/repositories/releases/uk/ac/ebi/beam/beam-core/. Forgot the command this morning.

**Pull request merged**
