### PR TITLE
Much needed TLC for AtomContainer

### PR DESCRIPTION
**Pull request by johnmay**
Clean up implementations and tighten up IAtomContainer API. A big one but should hopefully read okay. Here's a summary of each step. The tightening of the API causes some regressions which highlighted some simple mistakes (e.g. wrong variable being passed in).

#### Array growth

The growing of the backing arrays has been tweaked to follow the same scheme
as Java's ArrayList. We now grow by x1.5 rather than the fixed +10. Using 
ArrayList as the backing array is not possible at the moment as there are
current modifications deep in cdk-reaction, something to look at in future
though.

#### setAtom

Don't allow atoms to be set in any position (atomCount was not incremented)
also keep the container in a consistent state with regards to bonds etc. This
removes much of the need for the replaceAtomWithAtom utility function.

#### setAtoms/setBonds

Copy the arrays for safety/encapsulation. Could also wipe bonds on setAtoms()
but we'll leave that for now.

#### removeAtom/removeAtomAndConnectedElectronContainers

Add a new method ``removeAtomOnly`` that does what ``removeAtom`` used to do,
``removeAtom`` now also removes bonds and we deprecated
``removeAtomAndConnectedElectronContainers``. In existing code we're good because
``removeAtom(atom)`` followed by ``removeBond(bond)`` is extra work but safe.

###  getAtom/getBond/getSingleElectron

Bounds check the index. Currently we have situations like this:

```java
IAtomContainer atom = new AtomContainer(10, 0, 0, 0);
atom.getAtom(0); // null
atom.getAtom(11); // ArrayIndexOutOfBounds
```

### getMinBondOrder/getMaxBondOrder

Correct implementations and throw error for atoms not in the container. ``getBondOrderSum``
also needs fixing but I think it'll be better to deprecate it.

### getConnected...

We now throw an error if an atom does not belonging to the container is passed in.
Also deprecate getConnectedAtomCount which does nothing different from getConnectedBondCount.

I intend to replace the usage of NoSuchElementException with NoSuchAtomException but
will do that once that runtime patch is applied.

### CODE REVIEW

**Comment by johnmay** [comment]
@egonw Sorry for long commit, would it be possible to get this merged in this weekend? Wanted to do some more CDK work today but am waiting on this.

**Comment by egonw** [comment]
"Also deprecate getConnectedAtomCount which does nothing different from getConnectedBondCount"

Of course, except for the multi atom bonds :)

**Comment by johnmay** [comment]
but it didn't actually do that :-).

https://github.com/cdk/cdk/commit/49887fc5f1cd5b5aac8f59ea10f33f5ce55ea4df#diff-dbe5d4fee4e9a855d3f96521449265c5R674

**Comment by egonw** [comment]
That doesn't surprise me... over time original ideas and implementations diverged...

**Pull request merged**
