### PR TITLE
Invalid stereochemistry group causes infinite loop

### PR DESCRIPTION
**Pull request by marois**
We've encountered MDLV3000 molfiles with invalid stereo collections, i.e., SGroups (M  V30 MDLV30/STE???) with a bond collection instead of an atom collection. This causes the MDLV3000Reader to get stuck in an infinite loop in MDLV3000Reader::parseStereoGroup. Other libs, like Indigo, silently ignore this issue.

My PR throws a CDKException, but another approach could be to ignore when mode != Mode.STRICT.

### CODE REVIEW

**Comment by johnmay** [comment]
Looks good but I will test the file in BIOVIA tools. It is reasonable that stereogroups apply to bonds as well as atoms.

**Comment by johnmay** [comment]
Ah... it's applying it to wedge bonds not cis/trans. I was think (E/Z)-but-2-ene or (E*)-but-2-ene would be done this way.

**Comment by marois** [comment]
Note for the file used in the unit test: I copied an existing valid molfile (iterator/molV3000.mol), replaced the text ATOMS with BONDS, and saved that as the test mol file for this case. The bond IDs in the STEABS collection do not refer to actual stereo bonds.

**Comment by johnmay** [comment]
Do you have the actual example?

**Comment by marois** [comment]
Unfortunately, I've only seen it as a client's proprietary compound, so I cannot share it, but the infinite loop would be initiated with any text at the position not matching "ATOMS=("

**Comment by johnmay** [comment]
Can you say if the referenced bonds double bonds with cis/trans or wedge/hashes?

**Comment by johnmay** [comment]
I would make this a warning rather than an error, BIOVIA still read the file but ignore the information.

**Comment by marois** [comment]
What's weird is the SGroup references a single bond adjacent to the stereo bond, i.e. connected to an atom connected to a wedge. The highlighted bond in the attached image is the one referenced in the SGroup.
image

I'm good with making it a warning. The Biovia doc even mentions Biovia ignores this section when registering molecules.

What about Mode.STRICT? Do you want the code to also warn when in Mode.STRICT?

**Comment by johnmay** [comment]
Interesting it is likely an atropisomer, and would exhibit racemic behaviour. I will do some more tests on BIOVIA but I suspect this is an extension someone has tried to add without thinking about consequences. 

In you code you shouldn't be checking mode == STIRCT that is the job of handleError() function. If it's STRICT it throws an exception else prints a warning.

**Comment by marois** [comment]
Updated the code to let the errorHandler() function determine how to handle the error.

**Review by johnmay — APPROVED** [review]

**Pull request merged**
