### PR TITLE
Bumped the versions

### PR DESCRIPTION
**Pull request by egonw**
Maybe solves https://github.com/cdk/cdk/issues/862 without upgradeing to the latest Jena (see https://github.com/cdk/cdk/pull/748)

### CODE REVIEW

**Comment by egonw** [comment]
> I don't know too much about IORDF why do we need it, what advantages does the dependency bring?

I am not comfortable with this question. If we ask that about any functionality, we get very long discussions. For what purpose? CDK was designed as library of cheminformatics functionality, not to be a project to decide what is important (for someone) and what is not.

**Comment by johnmay** [comment]
My point was for the functionality of OWL you need it would perhaps be shorter just to write your own xml input/output

**Comment by johnmay** [comment]
See #748  should be good now once build is rounded up

**Comment by egonw** [comment]
No longer relevant.

**Pull request closed without merging**
