### PR TITLE
added a new reaction type to allow drawing '=' sign for a Net reaction

### PR DESCRIPTION
**Pull request by parit**
Currently, cdk doesn't allow to draw "=" to represent a 'Net reaction' as is present in most of the textbooks. This is also used the Rhea database to represent an 'Undirected' reaction. https://www.rhea-db.org/help/reaction-side-direction#Reaction_directions

This patch introduces a new reaction type, purely for the purpose of drawing. Please feel free to review and suggest changes.

### CODE REVIEW

**Comment by johnmay** [comment]
Do you have any more examples outside of RHEA? I think they just didn’t have the proper arrow types and it does not seem correct to me

**Comment by johnmay** [comment]
How many of these (#/%) are these in Rhea?
Can you also give more context on "net reaction" it's not something I'm familiar with.
I somewhat feel like perhaps a single line might be better, or make the '=' shorter by default. Note Rhea use "=>" which would normally be retrosynthetic. 

Orthogonal to this we probably need a BIDIRECTIONAL_UNBALANCED, MULTISTEP. The second doesn't really fit as a "direction" but would be useful.

For reference here are ChemDraw's arrows:
Screenshot 2023-06-23 at 08 59 02

**Comment by parit** [comment]
Hello,

In Rhea, there are separate forward, backward, bidirectional and undirected reactions for each transformation. So, for ex: 

https://www.rhea-db.org/rhea/23884 (undirected)
https://www.rhea-db.org/rhea/23885 (forward)
https://www.rhea-db.org/rhea/23886 (backward)
https://www.rhea-db.org/rhea/23887 (bi)

All these talk about the same transformation but directions are different. 

* I also prefer a shorter "=". Probably can play with scale to render an acceptable length with CDK.
* I agree => should be replaced with -> in Rhea and that's why looking into CDK for a better visualization.
* As of now, Rhea only uses => <= = <=>.  
* To be clear, the aim here is to only introduce "=" sign for undirected reactions only. 
* As per Net reaction, I think a multi-step reaction is cumulatively written with an equal to sign in Literature. So there is a precedence to use "=" in writing chemical reactions.
https://chemistry.stackexchange.com/questions/87086/what-does-an-equal-sign-mean-in-chemical-equations

**Comment by johnmay** [comment]
> However, it is useful in kinetics to distinguish this from a net reaction, which is written either with two one-sided arrows or an "equal" sign.

I think the two one sided arrow (EQUILIBRIUM) is now preferred there. (I'm on the working group for the new IUPAC reaction standards). 

If you make it a bit smaller (i.e. like an equal sign) then I will merge. You should be able to do this by just not drawing the lines to full length.

**Comment by johnmay** [comment]
> * https://chemistry.stackexchange.com/questions/87086/what-does-an-equal-sign-mean-in-chemical-equations

Yes I understand, I did my PhD in ChEBI :-). I was mere commenting on the linked page you have the following which shows an equilibrium arrow and '=' used interchangeably:

Screenshot 2023-06-27 at 20 53 33

I understand sometimes you don't know which direction it goes and that's useful for Rhea to differentiate that.

Like I said - make it smaller/prettier and I'll merge.

**Comment by redaschi** [comment]
> Yes I understand, I did my PhD in ChEBI :-)

I thought I had heard your name before :-)

> Like I said - make it smaller/prettier and I'll merge.

OK, got it. Thanks!

**Comment by parit** [comment]
@johnmay Hi, Sorry for the delay. I made some corrections. Please look at the generated image.

**Comment by johnmay** [comment]
No worries, looks good. A lot changed recently in the ReactionDepiction so I need to rebase. Will try and find time today.

**Comment by johnmay** [comment]
Alas the recent changes to the reaction drawing to support multi-step depictions were too much to rebase. I've redone the changes on the current main in #1009 and also tweaked the method a little to be a bit cleaner (avoiding the ``0.08`` fudge that was in there for sizing).

**Comment by johnmay** [comment]
Done in #1009

**Pull request closed without merging**
