### PR TITLE
Feature/advanced sgroup rendering

### PR DESCRIPTION
**Pull request by johnmay**
Adds much better rendering - for example >2 brackets and their direction, multiple groups, and mixtures.

Still need to add data display but didn't to figure how that works first.

efficientbits.blogspot.co.uk/2015/09/bringing-molfile-sgroups-to-cdk-demo.html

### CODE REVIEW

**Comment by johnmay** [comment]
Added some more commits for formatting labels nicely. All done now.

**Comment by johnmay** [comment]
Okay there was one more.

Code to generate them will be in a separate patch but here's a test file with some examples to try,
```
CHEBI:2956
  CDK     0911151902

 34 37  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145    0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145   -0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7145   -0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7145    0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1434   -2.0625    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
    2.1434   -2.8875    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.9684   -2.8875    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.9684   -2.0625    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
    3.7530   -3.1424    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
    4.2380   -2.4750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.7530   -1.8076    0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0
    4.9567   -2.8800    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.9567   -2.0700    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.0080   -3.9271    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.8149   -4.0986    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.4559   -4.5402    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.4289   -1.6500    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145   -2.0625    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145   -2.8875    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -1.6500    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
   -0.7145   -2.0625    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4289   -1.6500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4289   -0.8250    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.5600   -3.4709    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.9684   -1.2375    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145   -1.2375    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.4130   -2.4749    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -2.9280   -1.8075    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1434   -2.0625    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1434   -2.8875    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.9281   -3.1424    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.1829   -1.0229    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0 
 22  4  1  0  0  0  0 
  4  5  1  0  0  0  0 
  6  1  1  0  0  0  0 
  5  6  2  0  0  0  0 
  4  3  2  0  0  0  0 
  2  3  1  0  0  0  0 
  7  8  1  0  0  0  0 
  8  9  1  0  0  0  0 
 10  9  1  0  0  0  0 
 10  7  1  0  0  0  0 
  9 11  1  0  0  0  0 
 11 12  1  0  0  0  0 
 12 13  1  0  0  0  0 
 10 13  1  0  0  0  0 
 12 14  1  0  0  0  0 
 12 15  1  0  0  0  0 
 11 16  1  6  0  0  0 
 16 17  1  0  0  0  0 
 16 18  2  0  0  0  0 
  7 19  1  1  0  0  0 
 19 20  1  0  0  0  0 
 20 21  2  0  0  0  0 
 22 20  1  0  0  0  0 
 23 24  1  0  0  0  0 
 24 31  1  0  0  0  0 
 22 23  1  0  0  0  0 
 24 25  2  0  0  0  0 
  8 26  2  0  0  0  0 
 10 27  1  6  0  0  0 
 22 28  1  1  0  0  0 
 29 30  1  0  0  0  0 
 30 31  1  0  0  0  0 
 31 32  1  0  0  0  0 
 32 33  1  0  0  0  0 
 29 33  1  0  0  0  0 
 30 34  2  0  0  0  0 
M  STY  2   1 SUP   2 SUP
M  SAL   1  6   4   1   5   2   6   3
M  SBL   1  1   2
M  SMT   1 Ph
M  SAL   2  3  18  16  17
M  SBL   2  1  18
M  SMT   2 COOH
M  END
$$$$
CHEBI:3303
  CDK     0911151902

 71 75  0  0  0  0  0  0  0  0999 V2000
    2.8579    0.7219    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.1434    0.3094    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4289   -0.9281    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1434   -0.5156    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -0.9281    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145   -0.5156    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7145   -0.5156    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145    0.3094    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7145    0.3094    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4289   -0.9281    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4289    0.7219    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.7219    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4289    0.7219    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1434   -0.5156    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1434    0.3094    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.8579    0.7219    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.4125   -2.1977    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6674   -1.4130    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4125   -2.1977    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6674   -1.4130    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4744   -1.2415    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.0264   -1.8546    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9645   -2.8108    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8974   -2.8651    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7715   -2.6392    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.8579   -0.9281    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.5723   -0.5156    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    3.5723    0.3094    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.2868    0.7219    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.2868   -0.9281    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.2868   -1.7531    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.8579   -0.9281    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.5723   -0.5156    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -3.5723    0.3094    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.2868    0.7219    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.2868   -0.9281    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.2868   -1.7531    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.0013    0.3094    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    4.2868    1.5469    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.0837   -1.9666    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.5723   -2.1656    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -5.0013   -2.1656    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -3.5723   -2.1656    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -5.0013    0.3094    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -4.2868    1.5469    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.8579    1.5469    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.5724    1.9594    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1434    1.9594    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.8579    1.5469    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.5724    1.9594    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1434    1.9594    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -5.7158    0.7219    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -6.4302    0.3094    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -7.1447    0.7219    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -7.8592    0.3094    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -7.1447    1.5469    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -5.7158   -1.7531    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -6.4302   -2.1656    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -7.1447   -1.7531    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -7.8592   -2.1656    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -7.1447   -0.9281    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.7158    0.7219    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.4302    0.3094    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    6.4302   -0.5156    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.1447   -0.9281    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.0837   -2.7916    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.3692   -3.2041    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    4.3692   -4.0291    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.6548   -4.4416    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.8469   -1.0990    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.0837   -4.4416    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  0  0  0  0 
  4  2  2  0  0  0  0 
  3  4  1  0  0  0  0 
 18  5  1  0  0  0  0 
  5 20  1  0  0  0  0 
  6  3  2  0  0  0  0 
  5  6  1  0  0  0  0 
  5  7  1  0  0  0  0 
  6  8  1  0  0  0  0 
  7  9  1  0  0  0  0 
  7 10  2  0  0  0  0 
 11  2  1  0  0  0  0 
  8 11  2  0  0  0  0 
  9 12  1  0  0  0  0 
  8 12  1  0  0  0  0 
  9 13  2  0  0  0  0 
 10 14  1  0  0  0  0 
 13 15  1  0  0  0  0 
 14 15  2  0  0  0  0 
 15 16  1  0  0  0  0 
 17 18  1  0  0  0  0 
 19 17  1  0  0  0  0 
 17 24  2  0  0  0  0 
 19 20  2  0  0  0  0 
 23 19  1  0  0  0  0 
 20 21  1  0  0  0  0 
 21 22  2  0  0  0  0 
 22 25  1  0  0  0  0 
 25 23  2  0  0  0  0 
  4 26  1  0  0  0  0 
 26 27  1  0  0  0  0 
 27 28  1  0  0  0  0 
 28 29  1  0  0  0  0 
 27 30  1  0  0  0  0 
 30 31  1  0  0  0  0 
 14 32  1  0  0  0  0 
 32 33  1  0  0  0  0 
 33 34  1  0  0  0  0 
 34 35  1  0  0  0  0 
 33 36  1  0  0  0  0 
 36 37  1  0  0  0  0 
 29 38  1  0  0  0  0 
 29 39  2  0  0  0  0 
 31 40  1  0  0  0  0 
 31 41  2  0  0  0  0 
 37 42  1  0  0  0  0 
 37 43  2  0  0  0  0 
 35 44  1  0  0  0  0 
 35 45  2  0  0  0  0 
 16 46  1  0  0  0  0 
 46 47  1  0  0  0  0 
 46 48  2  0  0  0  0 
  1 49  1  0  0  0  0 
 49 50  1  0  0  0  0 
 49 51  2  0  0  0  0 
 44 52  1  0  0  0  0 
 52 53  1  0  0  0  0 
 53 54  1  0  0  0  0 
 54 55  1  0  0  0  0 
 54 56  2  0  0  0  0 
 57 58  1  0  0  0  0 
 58 59  1  0  0  0  0 
 59 60  1  0  0  0  0 
 59 61  2  0  0  0  0 
 42 57  1  0  0  0  0 
 38 62  1  0  0  0  0 
 62 63  1  0  0  0  0 
 63 64  1  0  0  0  0 
 64 65  1  0  0  0  0 
 40 66  1  0  0  0  0 
 66 67  1  0  0  0  0 
 67 68  1  0  0  0  0 
 68 69  1  0  0  0  0 
 64 70  2  0  0  0  0 
 68 71  2  0  0  0  0 
M  STY  6   1 SUP   2 SUP   3 SUP   4 SUP   5 SUP   6 SUP
M  SAL   1  4   1  51  50  49
M  SBL   1  1   1
M  SMT   1 OAc
M  SAL   2  4  16  46  48  47
M  SBL   2  1  20
M  SMT   2 OAc
M  SAL   3  4  55  54  56  53
M  SBL   3  1  57
M  SMT   3 OAc
M  SAL   4  4  59  58  61  60
M  SBL   4  1  61
M  SMT   4 OAc
M  SAL   5  4  70  63  64  65
M  SBL   5  1  67
M  SMT   5 OAc
M  SAL   6  4  68  71  69  67
M  SBL   6  1  71
M  SMT   6 OAc
M  END
$$$$
CHEBI:3756
  CDK     0911151902

 22 24  0  0  0  0  0  0  0  0999 V2000
    5.5601   -6.2116    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.9151   -6.7260    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.3644   -6.3952    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.7717   -6.3135    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    4.9151   -7.5510    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.5601   -8.0653    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    5.3765   -5.4073    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.2006   -6.3135    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.4861   -6.7260    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.3644   -7.8818    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.0571   -6.7260    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.7717   -5.4885    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    6.7224   -7.1385    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.9812   -4.8461    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.2006   -7.9635    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.4861   -7.5510    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.8788   -8.5268    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    6.7697   -5.0893    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    4.5882   -5.1641    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.7977   -4.0418    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.4045   -4.3598    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.0093   -3.7986    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  0  0  0  0 
  3  1  2  0  0  0  0 
  7  1  1  0  0  0  0 
  5  2  2  0  0  0  0 
  8  2  1  0  0  0  0 
 13  3  1  0  0  0  0 
  9  4  1  0  0  0  0 
 11  4  1  0  0  0  0 
 12  4  2  0  0  0  0 
  6  5  1  0  0  0  0 
 15  5  1  0  0  0  0 
 10  6  1  0  0  0  0 
 14  7  2  0  0  0  0 
 19  7  1  0  0  0  0 
  9  8  2  0  0  0  0 
 16  9  1  0  0  0  0 
 13 10  1  0  0  0  0 
 17 10  2  0  0  0  0 
 18 14  1  0  0  0  0 
 20 14  1  0  0  0  0 
 16 15  2  0  0  0  0 
 21 19  2  0  0  0  0 
 22 20  2  0  0  0  0 
 22 21  1  0  0  0  0 
M  CHG  1   4   1
M  CHG  1  11  -1
M  STY  1   1 SUP
M  SAL   1  3  11   4  12
M  SBL   1  1   7
M  SMT   1 NO2
M  END
$$$$
CHEBI:15597
  CDK     0911151902

 14 13  0  0  0  0  0  0  0  0999 V2000
   11.6783  -15.6796    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   12.8301  -16.3446    0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0
   13.9819  -17.0096    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   12.1651  -17.4964    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.8301  -18.6482    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.1601  -18.6482    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.8251  -19.8000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   14.8251  -17.4964    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.4951  -15.1927    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   12.1651  -19.8000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   10.8351  -18.4700    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   10.8351  -21.1300    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   10.8351  -19.8000    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0
    9.5051  -19.8000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  2  0  0  0  0 
  3  2  2  0  0  0  0 
  4  2  1  0  0  0  0 
  5  4  1  0  0  0  0 
  6  5  1  0  0  0  0 
  7  6  1  0  0  0  0 
  8  6  2  0  0  0  0 
  9  2  1  0  0  0  0 
  5 10  1  1  0  0  0 
 12 13  1  0  0  0  0 
 11 13  1  0  0  0  0 
 14 13  2  0  0  0  0 
 10 13  1  0  0  0  0 
M  CHG  1   7  -1
M  CHG  1   9  -1
M  CHG  1  11  -1
M  CHG  1  12  -1
M  STY  3   1 SUP   2 SUP   3 SUP
M  SAL   1  3   7   8   6
M  SBL   1  1   5
M  SMT   1 COO-
M  SAL   2  5  13  14  10  11  12
M  SBL   2  1   9
M  SMT   2 OPO3-2
M  SAL   3  4   9   2   1   3
M  SBL   3  1   3
M  SMT   3 SO3-
M  END
$$$$
```

**Comment by egonw** [comment]
A lot of code, but mostly internal. But looks good.

**Comment by egonw** [comment]
Applied and pushed.

**Comment by johnmay** [comment]
Thanks - yeah realising I needed the label reversing complicate things considerably.

**Comment by egonw** [comment]
There seem to be two more regressions: https://jenkins.bigcat.unimaas.nl/job/cdk/lastCompletedBuild/testReport/

    org.openscience.cdk.io.MDLV2000WriterTest.sgroupParentAtomListRoundTrip
    org.openscience.cdk.renderer.SymbolVisibilityTest.iupacCarbonCornerCase

**Comment by johnmay** [comment]
Darn - does travis not run the tests?

Regards,
John W May
john.wilkinsonmay@gmail.com

**Pull request closed without merging**
