### PR TITLE
Patch/bug 1356

### PR DESCRIPTION
**Pull request by johnmay**
second commit only

### CODE REVIEW

**Comment by egonw** [comment]
Why do you have a V2000 test file for the MDLReader?

BTW, I agree with your analysis... 10-15 years ago there still was a lot of MDL files around (pre V2000)... that has indeed become rare... if your new MDL reader supports V2000 as well as the older format, I am happy if that is the reader for both formats.... can your parser also run in STRICT mode on the pre-V2000 format?

But I am not sure what to do with this patch...

**Comment by johnmay** [comment]
The test file was the one given in the big report :)

**Comment by johnmay** [comment]
*bug

**Comment by egonw** [comment]
Ah, ok... yes, fair :)

Then I will make an additional unit test for this file to make sure it fails with the MDLReader when in STRICT mode :)

**Comment by johnmay** [comment]
The problem​ here is really that it's the CTab not the mol version. There
is only one molfile.

A nice API would be to have the molfile reader that selects the correct
CTab reader based on the header.

new MolfileReader() -> [CTabReader,CTabV2000Reader,CTabV3000Reader]

I kind of wanted to make the base API (AtomContainer/Atom/Bond) nicer
(rewrite) first though.

J

**Comment by egonw** [comment]
I'm good with the patch. I have created a follow up one to make sure in STRICT mode it fails:

https://github.com/egonw/cdk/compare/patch/bug1356

**Comment by egonw** [comment]
Have the constructor do that? I guess by embedding a more dedicated parser that would work... make sense for several formats, actually! Of course, there is the ReaderFactory that also sort of does this...

And what do you have in mind for the base API?

**Comment by johnmay** [comment]
> Have the constructor do that?

Yep... but that's the point there is no molfile v2000... only a molfile format - the internals shouldn't matter as to whether it's ctab v2000, v3000 etc. This is why the SDFReader handles them all :-).

> And what do you have in mind for the base API?

Just dreaming really but, to name a few
adjacency list data structure, less object use (int>Integer), memory efficiency, no Point2D/3D/ParitailPoint3D on Atoms (having them in a *conformer* like storage), bonds with only 2 atoms (I understand the logical of the current setup but it's just not useful and many existing algorithms simply don't work if they'r present - i.e. the graph algorithms presume an edge has two endpoints), no exception on clone(), much cleaner interfaces, less duplication (silent/data/debug are mostly the same this could be done much cleaner).

The API survived remarkably well but parts like good stereochemistry handling (rather than just wedge/hatch) just weren't considered and could be much cleaner with a redesign. Actually be interested if you had any of the original specs... I've seen the whiteboard somewhere before...

**Comment by egonw** [comment]
Superseded by this pull request: https://github.com/cdk/cdk/pull/121

**Pull request closed without merging**
