### PR TITLE
Various travis CI tweaks

### PR DESCRIPTION
**Pull request by mjw99**

### CODE REVIEW

**Comment by mjw99** [comment]
Hi Egon; it will run and test all the JVMs; there is an example of it in action here:

https://travis-ci.org/mjw99/cdk/builds/598044740

I have generally stuck to the LTS Java JVMs and then the latests not LTS in this test matrix.

**Comment by mjw99** [comment]
The javadoc aspect is having a few issues; I'll drop this aspect of the PR and return to it later.

**Comment by johnmay** [comment]
JavaDoc needs to the cdk-build-util package which isn't deployed to central. You need to install it locally first. This package include the custom Doclets etc. We could deploy it to central probably needs a better name though.

**Comment by johnmay** [comment]
https://github.com/cdk/cdk-build-util

**Comment by mjw99** [comment]
> JavaDoc needs to the cdk-build-util package which isn't deployed to central. You need to install it locally first. This package include the custom Doclets etc. We could deploy it to central probably needs a better name though.

OK, that's useful information; I did not know that. I think the JavaDoc aspect can be put in as a future task. The caching and multi JVM aspect, as it stands, seems to be working.

**Comment by johnmay** [comment]
https://github.com/cdk/cdk/wiki/Building-CDK

**Pull request merged**
