### PR TITLE
JNA InChI

### PR DESCRIPTION
**Pull request by johnmay**
Getting JNA InChI working in the CDK. This is functional with minimal test failures - mainly status codes. The current API is 100% preserved although I may add a simpler option.

### CODE REVIEW

**Comment by egonw** [comment]
Thank you! I compiled the CDK locally without test failures. I updated locally my Bacting to use the CDK 2.7 SNAPSHOT with JnaInChI and that worked fine too.

**Comment by johnmay** [comment]
Super - sorry should have added but it was just the first commit that had test failures. The other commits were making changes to tests that were all pretty minimal

**Comment by johnmay** [comment]
…so that everything passed

**Comment by egonw** [comment]
Yes, I think I got that :) At least one downstream case it working too. I pinged Daniel about functionality for checking InChI and -Keys, that JniInChI had. But very happy with the upgrade.

**Comment by rudolphi** [comment]
This change causes problems for projects where JMol is also present as dependency. Until CDK 2.6, this could be bypassed in pom.xml by
`		<dependency>
			<groupId>org.openscience.cdk</groupId>
			<artifactId>cdk-inchi</artifactId>
			<version>${cdk.version}</version>
			<exclusions>
				
				<exclusion>
					<groupId>net.sf.jnati</groupId>
					<artifactId>jnati-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>net.sf.jnati</groupId>
					<artifactId>jnati-deploy</artifactId>
				</exclusion>
				<exclusion>
					<groupId>net.sf.jni-inchi</groupId>
					<artifactId>jni-inchi</artifactId>
				</exclusion>
			</exclusions>
		</dependency>`

This no longer works for 2.7. Would it be possible to move the conflicting packages into a separate Maven project that we could exclude as well, using the ones from JMol instead?

**Comment by johnmay** [comment]
What problems does it cause? We can move JMol to JNI inchi as well

**Comment by johnmay** [comment]
Or is JMol all packed together into a single JAR so Maven can't sort out the dependencies. To be clear I can see this might be an issue now and agree we will move the JNI class to a separate modules.

**Comment by johnmay** [comment]
Please check that #795 fixes the issue

**Comment by rudolphi** [comment]
Thanks very much for your quick help, v 2.7.1 solved my problem:-)

**Pull request merged**
