### PR TITLE
add DefaultChemObjectReaderErrorHandler

### PR DESCRIPTION
**Pull request by uli-f**
Adds `DefaultChemObjectReaderErrorHandler` and sets as default for `DefaultChemObjectReader` and `DefaultIteratingChemObjectReader`. Misc javadoc fixes and small code changes in ILoggingTool and implementing classes.

### CODE REVIEW

**Comment by uli-f** [comment]
Closes #1111

**Comment by uli-f** [comment]
@johnmay @egonw Would appreciate any feedback on this :)

**Comment by egonw** [comment]
@johnmay, looks reasonable to me. What do you think?

**Review by egonw — APPROVED** [review]

**Comment by johnmay** [comment]
Sorry been busy but yes looks great. My one suggestion would be the default implementation should have another constructor which either takes an (existing) logger or the class. This way you get nicer error message in Log4J/SLF4J (e.g. o.o.c.i.MDLV2000Reader - ERROR - Invalid Bond Index).

**Comment by johnmay** [comment]
Oh sorry and that would be the default... I will leave a comment to annotate

**Comment by uli-f** [comment]
> Oh sorry and that would be the default... I will leave a comment to annotate

Thanks, the annotation made me better understand what you would like to see as an improvement. I hope the [latest commit](https://github.com/cdk/cdk/pull/1112/commits/42bead0fc0c7c6d67a1e4dc9f54bc1b5a8cfbf48) covers what you were referring to.

**Comment by johnmay** [comment]
Yep looks good - merged.

**Pull request merged**
