### PR TITLE
Create CITATION.cff

### PR DESCRIPTION
**Pull request by egonw**
@johnmay, `CITATION.cff` are recognized by GitHub and other platforms and indicate how the code in this repository should be cited.

One caveat, the current `CITATION.cff` mentions the specific CDK version and matching DOI. That works best when kept uptodate. The DOI is tricky, and is not know until after the release, and maybe you prefer to use the general CDK Zenodo DOI https://zenodo.org/doi/10.5281/zenodo.592588.

### CODE REVIEW

**Comment by larsgw** [comment]
`preferred-citation` should be an object, not an array (so remove the `- ` before `authors` and dedent the rest of the object, basically).

**Comment by johnmay** [comment]
Cool

**Comment by johnmay** [comment]
Maybe time for a new paper end of the year/2025.

**Comment by egonw** [comment]
> Maybe time for a new paper end of the year/2025.

I was thinking the same thing.

**Comment by egonw** [comment]
In action no `cdk/cdk`: 

image

**Pull request merged**
