### PR TITLE
add test dependencies assertj and mockito-junit-jupiter

### PR DESCRIPTION
**Pull request by uli-f**
I would like to add two dependencies to the parent `pom.xml` that facilitate writing tests:
- `assertj` with its fluent api is more modern and powerful compared to `hamcrest` when it comes to writing assertions
- `mockito-junit-jupiter` ties into the Junit5 lifecycle and provides annotations for mock instantiation and injection; this makes writing tests that use mockito mocks easier and more reliable

Both of these dependencies are only relevant for the maven scope `test` and would thus not impact on the size of shipped jars.

### CODE REVIEW

**Comment by johnmay** [comment]
Fine... but they're not used yet right?

**Comment by uli-f** [comment]
> Fine... but they're not used yet right?

Not yet, I would like to use them in the non-native (i.e., only based on `jna-inchi`) RInChI implementation.

Thanks for approving, makes writing tests (even) more fun!

**Comment by johnmay** [comment]
Yeah all good and looking forward to seeing, obv. make sure in ``<scope>test</scope>`` :-).

**Comment by johnmay** [comment]
BTW - https://efficientbits.blogspot.com/2013/04/assert-that-assert-this.html

**Comment by johnmay** [comment]
I never did add the custom matchers but defo fun to play around with.

```
Atom atom = new Atom();
atom.setSymbol("O");
        
assertThat(atom, is(carbon()));
 
// Expected: is carbon
//      but: was oxygen
```

**Pull request merged**
