### PR TITLE
Retrain of JPlogP to account for atomtypes in issue 629

### PR DESCRIPTION
**Pull request by plantej**

### CODE REVIEW

**Comment by plantej** [comment]
Retrain to fix issue 629

**Comment by plantej** [comment]
Do you mean to make 2 plots with the x axis being the experimental values from the Martell dataset and the y axis being the results from JPlogP using the current model for one plot  and the model from the paper for the other plot?  If so where should I put the png's of the plots  or should I just include the raw results in the comments somewhere with smiles strings as the structures?

**Comment by egonw** [comment]
Well, when we still had `CDK News` I would suggest to put the images there, but you can just copy/paste them in the issue tracker. I have no idea yet how we can archive the issue tracker at some point, but for the time being, we can go back to it (we could even use Internet Archive to make a copy). Or upload them to Figshare or so, and then we can even cite them in the source code :)

But I was just thinking of copy/pasting them in this tracker :) As support to check if there are no major regressions in the prediction. Of course, some overal RMSEP (etc) stats like reported in the article would also be most welcome.

That actually gives me an idea. You could also use PubPeer to report these on the updated model as comment on your paper. There is an "Additional info" category there, to make sure people recognize the PubPeer comment not as critique, but as, well, new material :)

**Comment by egonw** [comment]
See https://pubpeer.com/publications/56F6D7D51C88F59050E9A05A4B800F

**Comment by plantej** [comment]
Sounds good  I'll drop them there and post a link once it is done.

**Comment by johnmay** [comment]
Looks fine - add some suggestions to a PR on your repo. Fine to go as is but I think explicitly keeping the values is better, commented out they could be removed in future accidently.

**Comment by plantej** [comment]
I've tried to leave a comment with Pubpeer but they didn't like my email address. I've sent out a message to their contact, so hopefully it will be sorted, but interestingly, thelargest difference between the two predictions was 0.00473 and the majority of the differences were under 3.2e-4.  I'll post the graphs (Original vs Martel, Retrain vs Martel and Original vs Retrain) once they have sorted my login. I've included them here as well, but I think the pubpeer is a better storage place.
retrain
comparison
original

**Comment by plantej** [comment]
Updated pubpeer

**Comment by egonw** [comment]
> Looks fine - added some suggestions to a PR on your repo. Fine to go as is but I think explicitly keeping the values is better, commented out they could be removed in future accidently.

@plantej, did you do something with this feedback?

**Comment by plantej** [comment]
I just merged it in I think.  Should be good to go. It looks like there are 3 commits in this PR now so ready to rock and roll.

**Comment by egonw** [comment]
+1

@johnmay ?

**Comment by plantej** [comment]
It looks like the merge from @johnmay brought in a lot of other changes as well, but I suspect they are ones that would happen in the merge anyways.

**Pull request merged**
