### PR TITLE
codecov.io support

### PR DESCRIPTION
**Pull request by egonw**
As you suggest, let's not put the badge in the README, but I find the gaming it introducing personally helpful. I wrote this blog about the use for Bacting (per reviewer request): https://chem-bla-ics.blogspot.com/2020/12/bacting-code-coverage-jacoco-codecovio.html

### CODE REVIEW

**Comment by johnmay** [comment]
I find the way it reports in a comment quite obnoxious...

**Comment by johnmay** [comment]
... something more like how the checks are shown would be better IMO. 

Just reading up on your blog post now, but my two cents are we could just configure github actions to run the jacoco as a separate check? The visualisation is nice for a one off but it is needed for every small change. Perhaps more relevant for large user bases but typically for most patches you can judge a PR quickly how good the test coverage is, large "epic" work sets that add lots of functionality it is more important but in those cases if the reviewer cares that much they can run the coverage locally non?

**Comment by johnmay** [comment]
.. and sends me another spam email to delete.

I don't have any strong objection so feel free to merge but personally I don't think it's much of productivity improvement.

**Comment by egonw** [comment]
> I find the way it reports in a comment quite obnoxious...

I think I found how to turn that off.

**Comment by egonw** [comment]
> Perhaps more relevant for large user bases but typically for most patches you can judge a PR quickly
> how good the test coverage is, large "epic" work sets that add lots of functionality it is more important
> but in those cases if the reviewer cares that much they can run the coverage locally non?

Yes, agreed. I wasn't thinking so much as making this part of the patch review process either. I just want it to be calculated and updated and on their website to look at when I feel I want to. I'll merge it in and monitor that it doesn't spam us.

**Pull request merged**
