### PR TITLE
Formatted java files with help of maven coveo plugin.

### PR DESCRIPTION
**Pull request by javadev**
2437 files were changed. Sorry about it.

The command is:

mvn com.coveo:fmt-maven-plugin:2.9.1:format -Dstyle=aosp

### CODE REVIEW

**Comment by johnmay** [comment]
Is there a way to fine tune if, style is like a tooth brush - everyone has their own and don't want to use anyone else's. Personally I think the AOSP style is horrid, collapsing one line if statements, new line after parenthesis, yuk.

Nasty:
Screenshot 2021-08-24 at 08 14 13

Okay... but still think it was better before

Screenshot 2021-08-24 at 08 14 28

I can live with the non-aligned variable declarations, but 

```java
double width  = 5.0;
double height = 15.0;
```

is nicer than

```java
double width = 5.0;
double height = 15.0;
```

Also puts a newline on the function call, gross

Screenshot 2021-08-24 at 08 14 37

**Comment by johnmay** [comment]
Just to add, the javadoc looks better IMO. I do also like golang's approach where there is a fixed style [gofmt](https://go.dev/blog/gofmt).

**Comment by johnmay** [comment]
Let's backup, Why did you choose AOSP rather than the default - https://google.github.io/styleguide/javaguide.html?

**Comment by javadev** [comment]
> Let's backup, Why did you choose AOSP rather than the default - https://google.github.io/styleguide/javaguide.html?

I like aosp because of 4 spaces ident. We use this plugin in gradle for new spring-boot projects.

**Comment by johnmay** [comment]
Hmm, this does feel more like change for the sake of change. I would be more forgiving if you'd already contributed other changes (may have missed some?), but a first contribution to reformat the entire project (note it already used 4 spaces anyways) for personal preference is a bit odd to me. Imagine trying to purpose something like that to the Linux kernal for example as your first contribution :-).

To clarify I am not opposed to a simple to use consistent style and I think I would be more okay with the default google style, but I'll let @egonw decide.

**Comment by javadev** [comment]
It looks better in some places.

image

**Comment by johnmay** [comment]
That's not a counter example, the line is too long. The cases is messes up is where it undoes manually breaking and makes it worse. 

I've said what I need to say, will accept if it it's google style but no AOSP.

**Comment by javadev** [comment]
@johnmay It looks like only one person responsible for the project.

**Comment by egonw** [comment]
> @johnmay It looks like only one person responsible for the project.

the problem with styling is there as as many styling wishes as developers. So, I rather not change the styling preferences we have now. Another thought is, the gatekeeper (which is @johnmay currently) has a elevated vote here, since he's taking the final responsibility of what patches do in.

I like the style to make his work easy, so if this framework cannot do that, I rather not apply it.

**Comment by javadev** [comment]
AOSP is Google. Style is good, maven plugin is nice.

**Comment by egonw** [comment]
Okay, the patch is still using AOSP. That is currently a no go.

**Pull request closed without merging**
