### PR TITLE
The IFingerprinter API can be made backwards compatible with CDK 1.4.…

### PR DESCRIPTION
**Pull request by johnmay**
…x by re-adding and delegating the old method.

From writing the benchmarks for CDK 1.4 vs 2.0 it's clear to see where APIs have been broken unnecessarily. This patch re-adds the old IFingerprinter method reducing the barrier to code porting.

### CODE REVIEW

**Comment by egonw** [comment]
Hi @jonalv, this patch looks good to me, but could you please also glance over it?

**Comment by egonw** [comment]
@johnmay, there is a merge conflict that you may wish to resolve?

**Comment by johnmay** [comment]
Okay will resolve the conflict

**Comment by johnmay** [comment]
Rebased

**Comment by egonw** [comment]
I'll apply it once the hash test works properly again!

**Comment by johnmay** [comment]
hash test?

**Pull request merged**
