### PR TITLE
Eliminate commons-math3 dependency by reimplementing the MersenneTwis…

### PR DESCRIPTION
**Pull request by johnmay**
…ter logic. This was only used for a over-complicated PRNG used in the shortest path fingerprinter. A simpler linear-feedback shift PRNG would work just as well here but we want to keep backwards compatbility. Note this fingerprint it's really very good since the fingerprints are non-transativie and can't be used for substructure screening.

### CODE REVIEW

**Comment by johnmay** [comment]
Odd it broke... hmm I may just replace it with an XORSHIFT. This means the fingerprint no longer matches any existing versions - but I think that's okay since I don't think anyone uses it anyway :-).

**Comment by johnmay** [comment]
https://www.hyrumslaw.com/ :-)

**Comment by egonw** [comment]
> Odd it broke... hmm I may just replace it with an XORSHIFT. This means the fingerprint no longer matches any existing versions - but I think that's okay since I don't think anyone uses it anyway :-).

Fingerprints have been changing in the past between CDK versions. It would not be unheard of.

**Comment by johnmay** [comment]
I'll do that then :-).

**Comment by johnmay** [comment]
Okay much simpler now :-).

**Comment by egonw** [comment]
Looks good to me. Plz leave a note in the changelog that the FP changed in this version.

**Comment by johnmay** [comment]
Had already done the changelog note yesterday :-)

**Comment by johnmay** [comment]
https://github.com/cdk/cdk/wiki/2.7-Release-Notes

**Pull request merged**
