### PR TITLE
Added sonarcloud

### PR DESCRIPTION
**Pull request by javadev**

### CODE REVIEW

**Comment by javadev** [comment]
The bugs statistic.

image

**Comment by johnmay** [comment]
To fix this one @egonw https://sonarcloud.io/project/issues?id=egonw_cdk&resolved=false&rules=java%3AS2699&severities=BLOCKER&types=CODE_SMELL the helper method that calls assert needs to have "assert" in the name. Stupid :-).

Also a lot of the NPE are just Sonar Cloud now having good enough inspections.
https://sonarcloud.io/project/issues?id=egonw_cdk&resolved=false&rules=java%3AS2259&types=BUG

Chatting with Daniel Lowe about this and in general we weren't that impressed. I did clean up Beam though - https://sonarcloud.io/dashboard?id=johnmay_beam :-).

**Comment by egonw** [comment]
> Chatting with Daniel Lowe about this and in general we weren't that impressed.

Neither am I. It could be useful, but too many noise at this moment. I [asked them for guidance](https://twitter.com/egonwillighagen/status/1440366960861089797) on how to turn of false positives, but no reply :(

**Comment by johnmay** [comment]
Select the rule

Screenshot 2021-09-25 at 11 41 51

Then bulk change

Screenshot 2021-09-25 at 11 43 22

The non-assert thing actually is somewhat easy to fix and there might be genuine cases where there isn't an Assert.... but I would expect it to look inside functions and find them. Ah well

**Comment by egonw** [comment]
So, what do you think? shall we give it a go? is that what you mean? I have asked on Twitter if SonarCloud can be configured to not run certain tests, something possible with toolkits we used in the past. But no reply :(

**Comment by javadev** [comment]
It will be nice to merge it. Please send me generated key, organization, and project name for sonarcloud cdk.

**Comment by egonw** [comment]
Beside the lack of configuration, there is another loose end. We compile the CDK with two JDKs right now, but not sure how SonarCloud handles that

**Comment by javadev** [comment]
name: Build sonarcloud
    runs-on: ubuntu-latest

I see only jdk 11

**Comment by johnmay** [comment]
Needs fixes but would be good to get this in - have just added in JDK 17 as well I think it's fine to run the sonarcloud on a single JDK - I would actually say JDK 8 if possible since that's our current basis.

**Comment by javadev** [comment]
Good news. Please generate key for sonarcloud and send it to me.

**Comment by johnmay** [comment]
Did you have one already Egon? https://sonarcloud.io/project/issues?id=egonw_cdk

**Comment by javadev** [comment]
I expect to see sonarcloud for cdk.

**Comment by johnmay** [comment]
I have created the token now

**Pull request closed without merging**
