### PR TITLE
ISubstanceDescriptor API

### PR DESCRIPTION
**Pull request by egonw**
Please find here the pull request around further substance development. This PR is about the ISubstanceDescriptor API with one example descriptor. If the code is in order, I will backport more descriptors from NanoJava.

### CODE REVIEW

**Comment by johnmay** [comment]
Pull most in other request - add the lit ref one now. Note you can overwrite a pullrequest by pushing to the same branch.

**Comment by egonw** [comment]
The patches were actually different... I did not overwrite the branch, because I have no clue what would happen to all the comments... and I did not want to loose those.

**Comment by egonw** [comment]
John, the other patches had to be applied... I cleaned up stuff there... :(

Can you please revert those and apply these?

**Comment by johnmay** [comment]
So is it just this pull request substancedescriptor3 that needs to be applied I can ignore the other two?

**Comment by johnmay** [comment]
Okay from what I can tell the first two are still okay?

**Comment by egonw** [comment]
I think I changed at least one of them... should I check?

**Comment by egonw** [comment]
OK, yes, confirmed: the first two patches are identical.

**Comment by johnmay** [comment]
Okay fixed now.

**Comment by egonw** [comment]
Thanks!

**Pull request closed without merging**
