### PR TITLE
Patch/cxsmilesgen

### PR DESCRIPTION
**Pull request by johnmay**
Work in progress but made SMILES generation options more tunable.

 - Still to do CXSMILES for reaction, inc fragment grouping.
 - Documentation
 - improved canon 

```java
// SMILES generator that will only write tetrahedral stereo but not isotopes, or cis-trans etc.
SmilesGenerator smigen = new SmilesGenerator(SmiOpt.StereoTetrahedral | SmiOpt.Canonical);
```

### CODE REVIEW

**Comment by johnmay** [comment]
Okay reactions are done, actually turned out existing reactions weren't canonical. Just need to update documentation now which I'll try and get done tonight.

**Comment by egonw** [comment]
Looks ok to me, but I did not check all the bit operation stuff, which I am not using daily.

John, also, I cannot merge it, because there are conflicts that need manual resolving. Can you plz rebase the branch on the latest master?

**Comment by johnmay** [comment]
Resolved

**Comment by johnmay** [comment]
Thanks will get Nina's/Nickolays patch rebased tonight and reviewed properly.

**Pull request merged**
