### PR TITLE
Patch/remove old constants

### PR DESCRIPTION
**Pull request by egonw**
Removed unused constants and use IBond.Order directly.

### CODE REVIEW

**Comment by johnmay** [comment]
API change... please deprecate instead of remove.

**Comment by egonw** [comment]
[API change] Ah, fair point... I will update this patch.

**Comment by egonw** [comment]
@johnmay I've updated the patch:

- use @depecated
- undid the removal of the hybridization fields

**Comment by johnmay** [comment]
Looks good

**Pull request merged**
