### PR TITLE
Fix AtomContainer2.setStereoElements(List<IStereoElement>)

### PR DESCRIPTION
**Pull request by kazuyaujihara**
AtomContainer.setStereoElements(List <IStereoElement> element) checks for duplicate elements as described in the StereoElementFactory's comment, but AtomContainer2 version does not.

### CODE REVIEW

**Comment by johnmay** [comment]
This was actually intentional - notice the list is first emptied before adding everything. It's unlikely a stereo-element will appear twice (after all this is just reference equality) and so the de-duplication isn't useful.

Thoughts?

**Comment by kazuyaujihara** [comment]
I agree with you about addStereoElements method. On the other hand, it is better to check for duplication in addStereoElement method in my thought.
Anyway, the comment of StereoElementFactory class is to be revised.

**Comment by johnmay** [comment]
Fixed commend here: #398. 
The problem is the old AtomContainer used a Set<>, but since it's doing reference equality didn't really make sense. The comment in the StereoElementFactory was really referring to the fact that add elements did not clear any existing ones.

**Comment by kazuyaujihara** [comment]
I understand and confirmed the corrected comment in StereoElementFactory.

**Pull request closed without merging**
