### PR TITLE
Patch/sulphurtypes

### PR DESCRIPTION
**Pull request by johnmay**

### CODE REVIEW

**Comment by johnmay** [comment]
Note test failures I need to look at

**Comment by johnmay** [comment]
Rolled back problematic commit, whilst it's more correct to use valence in the CDK hydrogen added there was some legacy code that used just the hybridisation type and single bonds.

**Comment by egonw** [comment]
@johnmay, is this patch now good to go? Sulphurs are hard, thanks for this fix!

I think it's important to keep this perception code (not necessarily this implementation), but we do not always start with SMILES, and just may need to figure out the atom type from the input we get...

**Comment by johnmay** [comment]
Yes good to go

**Pull request merged**
