### PR TITLE
re-wrote tests for methods copy and extractSubstructure based on Hamc…

### PR DESCRIPTION
**Pull request by uli-f**
…rest's assertThat

### CODE REVIEW

**Review by egonw — APPROVED** [review]
I scrolled through it, and the restructuring is clear and I did not spot transcription errors.

**Comment by egonw** [comment]
@johnmay, am I blind, or did the tests not run on this? I don't see the test/coverage reports...

**Comment by uli-f** [comment]
@egonw Nope, tests didn't run 🤷🏼

**Comment by egonw** [comment]
> @egonw Nope, tests didn't run 🤷🏼

I cannot find how to manually get it started. Normally there is an option to run it. But not here. Maybe because this is a PR on a PR?

**Comment by egonw** [comment]
I tested it locally with Java11 and that does not give failing tests.

**Comment by uli-f** [comment]
> I cannot find how to manually get it started. Normally there is an option to run it. But not here. Maybe because this is a PR on a PR?

Yep, that seems like a good guess to me. Looking at #891 and #893 there aren't any checks available either.

**Comment by uli-f** [comment]
> I tested it locally with Java11 and that does not give failing tests.

I did the same on Java 17, all good 🟢

**Comment by johnmay** [comment]
Could be the permissions changes to the workflow that were suggested.

**Comment by johnmay** [comment]
Or maybe it's because this is a PR into another PR.

**Comment by johnmay** [comment]
The assertThat was just a suggestion BTW - didn't expect to use it :-)

**Pull request merged**
