### PR TITLE
Reuse parts from base path fingerprint.

### PR DESCRIPTION
**Pull request by johnmay**
Checked through derived classes - the only one that needed updating was the hybridisation fp.

### CODE REVIEW

**Comment by egonw** [comment]
See my comments just seconds ago...

**Comment by johnmay** [comment]
Does anything need to change on this?

**Comment by egonw** [comment]
That referred to this comment: https://github.com/cdk/cdk/pull/297#pullrequestreview-31716412

I don't have a particular request and if you don't either, after taking into account that comment, then I should apply this patch... (so, thanks for the ping :)

**Comment by johnmay** [comment]
We could make it extend the base Fingerprinter rather then duplicate but it's okay as it is.

**Comment by johnmay** [comment]
Actually it already extends it... give me two seconds and I'll delete the unnecessary code

**Pull request merged**
