### PR TITLE
Test jar removal

### PR DESCRIPTION
**Pull request by johnmay**
One of the complexities of CDK is the test dependencies. I believe it is possible to remove all these using a number of mechanisms. Currently due to these dependencies we upload 2x the number of JARs to central. At minimum we could minimise the scope of what gets uploaded (e.g. really optimally just be cdk-testdata, cdk-test). However if we get to that point we can actually just move their code to the main/ path and then build them as normal jars that are only included for tests.

```
   1             <artifactId>cdk-libiocml</artifactId> DONE - dupe roundTrip method
   1             <artifactId>cdk-qsaratomic</artifactId> DONE - deprecated code, simplify test
   1             <artifactId>cdk-qsarbond</artifactId> DONE - deprecated code, simplify test
   1             <artifactId>cdk-renderbasic</artifactId> DONE - dupe required base classes
   1             <artifactId>cdk-test-standard</artifactId> DONE - move fp tests from standard
   2             <artifactId>cdk-qsarmolecular</artifactId> DONE 1/2 - deprecated code, simplify test
   3             <artifactId>cdk-test-interfaces</artifactId> DONE - simplify cdk-diff allowing us to use it in cdk-test and remove cdk-test-interfaces completely
   4             <artifactId>cdk-test-core</artifactId> DONE - trivial relocation of helper classes
   5             <artifactId>cdk-io</artifactId> DONE - need IRgroupList/IRgroup and some mocking. Rather than test different ChemObject types (the doc was wrong about NoNotify being checked) we just use the interfaces.
  25             <artifactId>cdk-data</artifactId> DONE - move TestMoleculeFactory to the main/ code. This is a little off - a better more more involved option would be make the caller provide a builder
   5             <artifactId>cdk-qsar</artifactId> DONE - move interfaces to cdk-interfaces and DescriptorTest to CDK test. We also then need a new init that takes a builder
   2             <artifactId>cdk-qsarmolecular</artifactId> DONE 2/2 qsarprotein could be folded into to qsarmolecule but for ow I duplicated the test MolecularTest
```

Will handle these in a separate PR
```
  29             <artifactId>cdk-testdata</artifactId>
  47             <artifactId>cdk-test</artifactId>
```

### CODE REVIEW

**Comment by johnmay** [comment]
Good to go now - build should pass. The main comment details the order things were done. The cdk-io was probably the most tricky 30bead8 to 3863b76

**Comment by egonw** [comment]
Looks good, compiles here locally fine.

**Comment by johnmay** [comment]
Thanks - I think when I first did the maven modularisation I lacked the energy/motivation to do this but am excited to get it all working more smoothly. 

I don't think it will make the build faster (although a "clean install" on my laptop is now only 1 min which is fast enough) but the OSSRH upload should be faster and the removal of the test dependencies makes the project more approachable since it's a quirk that doesn't need to be thought about.

**Comment by egonw** [comment]
Pushing the SNAPSHOT as we type :)

**Comment by johnmay** [comment]
Ah well until the next PR it won't get faster :-)

**Comment by johnmay** [comment]
In the parent pom we have:

```
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
                <inherited>true</inherited>
                <configuration>
                    <archive>
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                            <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

What I probably should have done was narrow the scope to just those that need it.... however like I said I believe I can completely remove this need completely which is even better

**Pull request merged**
