### PR TITLE
Name Nihonium, Moscovium, Tennessine, and Oganesson.

### PR DESCRIPTION
**Pull request by johnmay**

### CODE REVIEW

**Comment by johnmay** [comment]
Ready for when they're approved. Just have to wait two months :-)

**Comment by egonw** [comment]
John, if you split this patch in file (whitespace) restructing and the actual addition, the first can be applied now, and the latter becomes a whole lot simpler (smaller), increasing the chance it still applies this autumn...

**Comment by johnmay** [comment]
Done

**Comment by egonw** [comment]
OK, the first patch is now applied to master. Thanks!

**Comment by egonw** [comment]
There is news from IUPAC, I heard: https://twitter.com/Larsohrstrom/status/803871908236296192

**Comment by egonw** [comment]
@johnmay, I can resolve the conflicts here... unless you want to rebase the patches yourself? Plz let me know...

**Comment by johnmay** [comment]
I'll fix the conflicts... actually bad names but they knew (read the document).

**Ts** is normally used for **Tosyl**, they say a chemist would never confuse the two but of course teaching a computer that is a little more tricky... well other than to just ban them.

**Nh** is more fun... consider ``[Nh]`` ins SMARTS used be aliphatic nitrogen with one implicit hydrogen. I think probably the fix here is ban the bottom rows from SMARTS symbols and suggest using '#<num>' syntax instead.

**Comment by egonw** [comment]
Oh, wonderful points! @rajarshi, what do you think? Should we invite @johnmay for a JCheminf Commentary (http://jcheminf.springeropen.com/submission-guidelines/preparing-your-manuscript/commentary) to write up the implications to cheminformatics (i.e. outlining some of the (open) standards that need updating? I'd be happy with even shorter than 800 words...

**Comment by rajarshi** [comment]
Yes, that would certainly be welcome. @johnmay raises a good point - standards committees might consult with informatics to ensure that they're standards don't impede informatics handling

**Comment by johnmay** [comment]
They asked for comment but it had already been pointed out to them​ that
Ts=Tosyl. If you want a commentary on this, Roger would be better - the Nh
example is from him.

**Comment by egonw** [comment]
@johnmay or both...

**Comment by egonw** [comment]
(oops, wrong button)

**Pull request closed without merging**
