### PR TITLE
Absolute Smiles JNI-inchi fix

### PR DESCRIPTION
**Pull request by dkatzel-ncats**
This is the fix for #797 as well as adding the fix for 2.7.1 to the 2.8 branch.

This is as small a change as possible.  Alternative approaches are to make the inchi options and return value Strings instead of enums so there wouldn't be a dependency for either JNA or JNI inchi.  but there would then be a lot more String parsing into those enums every time which would might lead to  performance problems.

Another approach would be to make a CDK inchi interface that wraps the underlying JNI/JNA implementation but that would be more code changes and API breaking changes.

### CODE REVIEW

**Comment by egonw** [comment]
I think the idea is to fix this by (runtime?) depending on the new `cdk-jniinchi-support` module, @johnmay?

**Comment by dkatzel-ncats** [comment]
yeah I wasn't sure if the idea going forward was to assume JNA-inchi and have additional support for jni so things should default to jna or if you wanted to make it more flexible based on which modules are loaded?

**Comment by egonw** [comment]
@dkatzel-ncats, can you try the current `master` (so, without this patch), but add this to your `pom.xml`:

```xml
    <dependency>
      <groupId>org.openscience.cdk</groupId>
      <artifactId>cdk-jniinchi-support</artifactId>
      <version>${cdk.version}</version>
    </dependency>
```

Does that solve it?

**Comment by dkatzel-ncats** [comment]
That would fix the compiler error but my downstream software can't use JNI inchi we must use JNA

**Comment by egonw** [comment]
No, I think this `cdk-jniinchi-support` module just provides the two classes, but not actually use the JNI version... checking!

**Comment by egonw** [comment]
@dkatzel-ncats, check https://github.com/cdk/cdk/tree/master/storage/jniinchi-support/src/main/java/net/sf/jniinchi and if you like that module's pom file too... I think it's really just these two classes.

**Comment by johnmay** [comment]
Yep include the jniinchi-support-module for now, not doing another release sorry am swamped ATM.

**Comment by johnmay** [comment]
I'll fix on master though, it's just a mater of not using the INCHI_OPTION etc

**Comment by johnmay** [comment]
To clarify as Egon said it's jus the Enum's not the actual JNI stuff. It's basically to provide backwards compatible API support, everything still uses JNA inchi.

**Comment by dkatzel-ncats** [comment]
I can confirm using 2.7.1 with jniinchi-support to my software that uses cdk does make everything work using 2.7.1  thanks!

**Pull request closed without merging**
