### PR TITLE
Patch/alogp fixup

### PR DESCRIPTION
**Pull request by johnmay**
Following analysis form #538, various tweaks to align closer with VEGA. Now in to diminising returns. Testing on 10K from ChEMBL we previously had an RSME of 7.14 and is now 0.10 with 86% of compounds have a LogP < 0.01 abs diff. 

Before:
```
Sample Size:    10000
N < 0.01 diff:  1048
Difference Sum: 15542.94
RMSE:           7.14
```

Now
```
Sample Size:    10000
N < 0.01 diff:  8665
Difference Sum: 838.09
RMSE:           0.10
```

### CODE REVIEW

**Comment by johnmay** [comment]
Still needs a rewrite but useful exercise

**Comment by egonw** [comment]
Great work! I'll check the patches asap.

**Comment by johnmay** [comment]
Ah need to fix something that broke due to my tweak with the EState stuff (allowing it to handle implh).

**Comment by johnmay** [comment]
Should be fixed, need a null check on hydrogen count

**Pull request merged**
