### PR TITLE
Patch/atomtype missing valency

### PR DESCRIPTION
**Pull request by johnmay**
Should fix most of failures... I've also tightened up the immutable atom type instance so we'll get fails elsewhere at attempts to change the values.

### CODE REVIEW

**Comment by johnmay** [comment]
Hmm looks like still some problems with other parts but should be easy to fix.

**Comment by egonw** [comment]
[Immutable] maybe we can discuss splitting mutable/immutable in Cambridge for CDK 2.2 ?

**Comment by johnmay** [comment]
RDKit splits out a ROMol and a RWMol... it causes nothing but problems as you end up needing to create new molecules all the time. I am in favour through of immutable atom properties etc though.

**Comment by johnmay** [comment]
just fixed the new failures which look to be due to missing values in some XML configs.

**Pull request merged**
