### PR TITLE
restore space as delimiter for string-based definition of InChI options

### LINKED ISSUE #845: Option for InChIGenerator: comma or space delimited?
Hi!
this is just to record a small inconsistency in the behavior from 2.6 to 2.7. In particular, while the javadoc for [InChIGeneratorFactory.getInChIGenerator(IAtomContainer container, String options)](https://github.com/cdk/cdk/blob/master/storage/inchi/src/main/java/org/openscience/cdk/inchi/InChIGeneratorFactory.java#L148) does not specify how to separate the options in the string, the underlying [InChIGenerator(IAtomContainer atomContainer, String optStr, boolean ignoreAromaticBonds)](https://github.com/cdk/cdk/blob/master/storage/inchi/src/main/java/org/openscience/cdk/inchi/InChIGenerator.java#L155-L157) specifies "optStr: Space delimited string of options...". 
From release 2.6 to 2.7, the behavior has changed from accepting only space separated to accepting only comma separated string. In 2.7 space-separated options trigger the "Unrecognised InChI option" warning message.

Here is how to see the different behavior:
```
    	SmilesParser sp = new SmilesParser(DefaultChemObjectBuilder.getInstance());
    	IAtomContainer iac = sp.parseSmiles("C[C@H](Cl)F");
        InChIGeneratorFactory factory = InChIGeneratorFactory.getInstance();
        try {
		InChIGenerator genComma = factory.getInChIGenerator(iac,"FixedH, SNon");
		System.out.println("With comma-separated options: "+genComma.getInchi());
	} catch (CDKException e) {
		System.out.println("With comma-separated options: "+e.getMessage());
	}
        InChIGenerator genSpace = factory.getInChIGenerator(iac,"FixedH SNon");
        System.out.println("With space-separated options: "+genSpace.getInchi());
```

With release 2.6 (from maven) the output is:
```
With comma-separated options: InChI generation failed: Unrecognised InChI option
With space-separated options: InChI=1/C2H4ClF/c1-2(3)4/h2H,1H3
```

With release 2.7.1 (from maven) the output is:
```
With comma-separated options: InChI=1/C2H4ClF/c1-2(3)4/h2H,1H3
org.openscience.cdk.inchi.InChIOptionParser WARN: Ignore unrecognized InChI flag:null
With space-separated options: InChI=1S/C2H4ClF/c1-2(3)4/h2H,1H3/t2-/m1/s1
```

Using [getInChIGenerator(IAtomContainer container, InchiOptions options)](https://github.com/cdk/cdk/blob/master/storage/inchi/src/main/java/org/openscience/cdk/inchi/InChIGeneratorFactory.java#L197) is a way to by-pass the parsing problem entirely.

Still, I wanted to fix to the documentation adding which separator is expected, but then I realized I do not know if the change of separator from space to comma is intentional. So, is it intentional?

### PR DESCRIPTION
**Pull request by marco-foscato**
Fixes #845

### CODE REVIEW

**Comment by johnmay** [comment]
Thanks just running the tests but looks fine - I wonder if maybe it should be both String and Comma - it definitely used to be space though as I noted it was essentially like command line args. "-15T -KET" etc - annoyingly on Windows you needed to use "/15T /KET"

**Comment by marco-foscato** [comment]
> I wonder if maybe it should be both String and Comma

Me too. I'm sending a new PR where one can use both comma and space.

**Comment by marco-foscato** [comment]
> I'm sending a new PR

Actually, it's not a "new PR". I've committed the new changes to this same branch, so it already in this PR.

**Comment by johnmay** [comment]
Thanks

**Pull request merged**
