### PR TITLE
Fixed the OSGi meta data export

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/cdk/cdk/issues/1006

### CODE REVIEW

**Comment by egonw** [comment]
I'll check the results, but the approach is very interesting!

**Comment by Mailaender** [comment]
I tested using https://stackoverflow.com/questions/13834141/create-local-maven-repository

**Comment by johnmay** [comment]
Ah so was is the test-jar dependencies messing things up? I’ve tried to untangle that as much as possible but it turns out retroactively segregating code into modules is tricky and takes time

**Comment by egonw** [comment]
> Ah so was is the test-jar dependencies messing things up?

That came unexpected to me too!

**Comment by egonw** [comment]
@Mailaender, I am not really an OSGi expert, and learning here. I looked at two `META-INF/MANIFEST.MF` files now, for `core` and `interfaces`. I notices that in the second before you patch, I do get exported packages:

```
Manifest-Version: 1.0
Created-By: Apache Maven Bundle Plugin 5.1.8
Build-Jdk-Spec: 11
Specification-Title: cdk-interfaces
Specification-Version: 2.10
Implementation-Title: cdk-interfaces
Implementation-Version: 2.10-SNAPSHOT
Bnd-LastModified: 1697611659779
Bundle-Description: Modular library for Cheminformatics
Bundle-License: http://www.gnu.org/licenses/lgpl.html
Bundle-ManifestVersion: 2
Bundle-Name: cdk-interfaces
Bundle-SymbolicName: org.openscience.cdk.interfaces
Bundle-Version: 2.10.0.SNAPSHOT
Export-Package: org.openscience.cdk;version="2.10.0",org.openscience.cdk
 .event;version="2.10.0",org.openscience.cdk.exception;version="2.10.0",
 org.openscience.cdk.graph.matrix;version="2.10.0",org.openscience.cdk.h
 ash;uses:="org.openscience.cdk.interfaces";version="2.10.0",org.opensci
 ence.cdk.interfaces;uses:="javax.vecmath";version="2.10.0",org.openscie
 nce.cdk.io;uses:="org.openscience.cdk.exception,org.openscience.cdk.int
 erfaces,org.openscience.cdk.io.formats,org.openscience.cdk.io.listener,
 org.openscience.cdk.io.setting";version="2.10.0",org.openscience.cdk.io
 .formats;version="2.10.0",org.openscience.cdk.io.iterator;uses:="org.op
 enscience.cdk.interfaces,org.openscience.cdk.io";version="2.10.0",org.o
 penscience.cdk.io.iterator.event;uses:="org.openscience.cdk.interfaces,
 org.openscience.cdk.io";version="2.10.0",org.openscience.cdk.io.listene
 r;uses:="org.openscience.cdk.io,org.openscience.cdk.io.setting";version
 ="2.10.0",org.openscience.cdk.io.random;version="2.10.0",org.openscienc
 e.cdk.io.setting;uses:="org.openscience.cdk.exception,org.openscience.c
 dk.interfaces";version="2.10.0",org.openscience.cdk.isomorphism.matcher
 s;uses:="org.openscience.cdk.interfaces";version="2.10.0",org.openscien
 ce.cdk.libio.cml;uses:="org.openscience.cdk.interfaces";version="2.10.0
 ",org.openscience.cdk.qsar;uses:="org.openscience.cdk,org.openscience.c
 dk.exception,org.openscience.cdk.interfaces";version="2.10.0",org.opens
 cience.cdk.qsar.result;version="2.10.0",org.openscience.cdk.tools;versi
 on="2.10.0"
Import-Package: javax.vecmath,org.openscience.cdk,org.openscience.cdk.ex
 ception,org.openscience.cdk.interfaces,org.openscience.cdk.io,org.opens
 cience.cdk.io.formats,org.openscience.cdk.io.listener,org.openscience.c
 dk.io.setting
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-6.3.1.202206071316
```

But after the patch, I see none:

```
Specification-Title: cdk-interfaces
Specification-Version: 2.10
Implementation-Title: cdk-interfaces
Implementation-Version: 2.10-SNAPSHOT
Bnd-LastModified: 1697610545301
Bundle-Description: Modular library for Cheminformatics
Bundle-License: http://www.gnu.org/licenses/lgpl.html
Bundle-ManifestVersion: 2
Bundle-Name: cdk-interfaces
Bundle-SymbolicName: org.openscience.cdk.interfaces
Bundle-Version: 2.10.0.SNAPSHOT
Import-Package: javax.vecmath
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-6.3.1.202206071316
```

Should packages with interfaces not be declared as exported too?

**Comment by Mailaender** [comment]
You are right, this does not work at all. I must have developed against a cached version.

**Pull request closed without merging**
