### PR TITLE
Use a matrix-based build

### PR DESCRIPTION
**Pull request by egonw**
I learned a new GitHub Action trick today :)

### CODE REVIEW

**Comment by egonw** [comment]
I checked the check fail, and it doesn't make sense to me. It seems to not be able to find a dependency of the Maven compiler .... but, but, but...

**Comment by johnmay** [comment]
Me neither, why Java 14 and not 15?

**Comment by johnmay** [comment]
I think the issue is that plugin doesn't support Java 14+ ATM?

```
Examples of version specifications that the java-version parameter will accept:

A major Java version

e.g. 6, 7, 8, 9, 10, 11, 12, 13, ...

A semver Java version specification

e.g. 8.0.232, 7.0.181, 11.0.4

e.g. 8.0.x, >11.0.3, >=13.0.1, <8.0.212

An early access (EA) Java version

e.g. 14-ea, 15-ea

e.g. 14.0.0-ea, 15.0.0-ea

e.g. 14.0.0-ea.28, 15.0.0-ea.2 (syntax for specifying an EA build number)

Note that, per semver rules, EA builds will be matched by explicit EA version specifications.

1.x syntax

e.g. 1.8 (same as 8)

e.g. 1.8.0.212 (same as 8.0.212)

```

**Comment by egonw** [comment]
that 14 would not be supported doesn't make sense to me... I copied the set up from here: https://github.com/egonw/bacting/actions/runs/452612639 ! I will try to figure out tomorrow what is different.

**Comment by johnmay** [comment]
I was going by the doc explicitly stops at 13 abs shows 14-ea. Since Java 12,13,14 are basically public betas.... I would just do 15-ea or whatever the coding is

**Comment by johnmay** [comment]
But yes odd it works there

**Comment by egonw** [comment]
Okay, we just compile 8 and 11 then?

**Comment by johnmay** [comment]
Could you disable the codecov comment?

**Comment by egonw** [comment]
> Could you disable the codecov comment?

that is what https://github.com/cdk/cdk/blob/master/codecov.yml is supposed to do...

**Comment by johnmay** [comment]
¯\_(ツ)_/¯

**Comment by egonw** [comment]
Maybe it still posted it because that file was not part of this branch/PR. We'll see.

**Pull request merged**
