### PR TITLE
add javadocs to RdfileReader and RdfileRecord, make RdfileReader final

### PR DESCRIPTION
**Pull request by uli-f**
@johnmay I didn't quite expect for you to go all in and merge #942 , so here is a separate PR with a few additions to the javadocs. Only code change is to make `RdfileReader` `final`.

### CODE REVIEW

**Comment by egonw** [comment]
Looks good to me. @uli-f, what is the advantage of having a class final?

**Comment by uli-f** [comment]
> Looks good to me. @uli-f, what is the advantage of having a class final?

@egonw Declaring a class final prevents it from being inherited. That guarantees that the class behaves as intended as its method cannot be overridden. imo, guaranteeing behavior is a fair call for API classes in general. There are also performance enhancements for certain ops that the JVM can make for final classes, but I don't know how significant they actually are...

**Comment by egonw** [comment]
> There are also performance enhancements for certain ops that the JVM can make for final classes, but I don't know how significant they actually are...

Yeah, that was what I was wondering. Because making it final, as you say, makes it harder to tweak the functionality (e.g. for custom changes to the format, etc). The CDK becomes less flexible. And I honestly am just thinking out loud here and do not know the right answer.

**Comment by johnmay** [comment]
> > There are also performance enhancements for certain ops that the JVM can make for final classes, but I don't know how significant they actually are...
> 
> Yeah, that was what I was wondering. Because making it final, as you say, makes it harder to tweak the functionality (e.g. for custom changes to the format, etc). The CDK becomes less flexible. And I honestly am just thinking out loud here and do not know the right answer.

By view is APIs should generally be as restrictive as possible, e.g. final/private/package-private to avoid bloat and give strong encapsulation. It's very easy to add something in but very difficult to take something out. In this case, making a class final by default - it is very easy (non breaking) to make this non-final if needed, conversely if it's non-final and then we want to make it final then it's a break change and much more difficult. Same with visibility. 

Inheritance/public by default can be overused and some other languages are baking this - e.g. in rust things are immutable by default and you must explicitly make them "mut"able.

**Comment by uli-f** [comment]
> My view is APIs should generally be as restrictive as possible, e.g. final/private/package-private to avoid bloat and give strong encapsulation.

I fully agree with this.

I don't know if there are any coding guidelines for CDK - if so, it might be worthwhile to add this statement.

**Pull request merged**
