### PR TITLE
Updated version: 2.20.1 has a forkBooster bug

### PR DESCRIPTION
**Pull request by egonw**
On our Jenkins I'm getting a forkBooster exception, which is reported for 2.20.1 (and one other version). An alternative solution is to no allow forking. The phenotype is:

```
Please refer to /var/lib/jenkins/jobs/cdk/workspace/app/depict/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /var/lib/jenkins/jobs/cdk/workspace/app/depict && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dcdk.logging.level=ERROR -jar /var/lib/jenkins/jobs/cdk/workspace/app/depict/target/surefire/surefirebooter4348128345109234029.jar /var/lib/jenkins/jobs/cdk/workspace/app/depict/target/surefire 2018-11-10T13-46-13_110-jvmRun1 surefire5636495753901702235tmp surefire_493219910478475493137tmp
Error occurred in starting fork, check output in log
Process Exit Code: 1
org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /var/lib/jenkins/jobs/cdk/workspace/app/depict && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dcdk.logging.level=ERROR -jar /var/lib/jenkins/jobs/cdk/workspace/app/depict/target/surefire/surefirebooter4348128345109234029.jar /var/lib/jenkins/jobs/cdk/workspace/app/depict/target/surefire 2018-11-10T13-46-13_110-jvmRun1 surefire5636495753901702235tmp surefire_493219910478475493137tmp
Error occurred in starting fork, check output in log
Process Exit Code: 1
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:679)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:279)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:243)
```

Our Jenkins job: https://jenkins.bigcat.unimaas.nl/job/cdk/

### CODE REVIEW

**Comment by egonw** [comment]
Carp... ignore this one.

**Comment by johnmay** [comment]
Use 3.0.0-M?

**Comment by johnmay** [comment]
Almost certainly a Jenkins issue. Hint Travis CI is fine and the CLI building is fine :-)

**Comment by egonw** [comment]
OK, sounds good then. Let's give that a go. I'll check here if it solve this local issue: https://github.com/cdk/cdk/issues/507 (which does not seems to show up elsewhere...)

**Comment by johnmay** [comment]
Just disable the forking if needed.

**Comment by egonw** [comment]
Disabling forking helps, but that's when I got stuck with https://github.com/cdk/cdk/issues/507 :(

**Comment by egonw** [comment]
I'll continue investigating... (and I'll try to compile stuff at home more anyway, bc I'm seeing more local regressions that don't show up on Jenkins nor Travis CI... (but I doubt my system is that weird, that I'm really the only one :)

**Comment by johnmay** [comment]
What regressions are you seeing? As always make sure you're doing a clean build - only needed when large parts move. Also will likely need to wipe out the Jenkins Workspace. 

Moving the SMARTS stuff to cdk-legacy was safe but you if you have cached parts of a build it won't know what to do. Partially more complicated due to to JAVACC parser stuff.

**Comment by egonw** [comment]
It's local here, with the same command as the InChI thingy:

```shell
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 mvn -Dmaven.test.failure.ignore=true install
```

The errors I'm getting (but did not report it yet, as I haven't explored it yet; trying to make some other deadlines first):

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openscience.cdk.layout.CorrectGeometricConfigurationTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.116 s - in org.openscience.cdk.layout.CorrectGeometricConfigurationTest
[INFO] Running org.openscience.cdk.layout.StructureDiagramGeneratorTest
[INFO] Tests run: 49, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.935 s - in org.openscience.cdk.layout.StructureDiagramGeneratorTest
[INFO] Running org.openscience.cdk.layout.NonPlanarBondsTest
[INFO] Tests run: 29, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 s - in org.openscience.cdk.layout.NonPlanarBondsTest
[INFO] Running org.openscience.cdk.layout.IdentityTemplateLibraryTest
[ERROR] Tests run: 7, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.006 s <<< FAILURE! - in org.openscience.cdk.layout.IdentityTemplateLibraryTest
[ERROR] store(org.openscience.cdk.layout.IdentityTemplateLibraryTest)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is "[C][C][O] |(.0,1.0,;2.0,3.0,;4.0,5.0,)|\n[C][C] |(.0,1.0,;2.0,3.0,)|\n"
     but: was "[C][C][O] |(,0,1,0,;2,0,3,0,;4,0,5,0,)|\n[C][C] |(,0,1,0,;2,0,3,0,)|\n"
        at org.openscience.cdk.layout.IdentityTemplateLibraryTest.store(IdentityTemplateLibraryTest.java:128)

[ERROR] encodeEntry(org.openscience.cdk.layout.IdentityTemplateLibraryTest)  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is "CO |(12.5,5.5,;4.0,2.0,)|"
     but: was "CO |(12,5,5,5,;4,0,2,0,)|"
        at org.openscience.cdk.layout.IdentityTemplateLibraryTest.encodeEntry(IdentityTemplateLibraryTest.java:71)

[ERROR] encodeCoordinates(org.openscience.cdk.layout.IdentityTemplateLibraryTest)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is "|(12.5,5.5,;4.0,2.0,)|"
     but: was "|(12,5,5,5,;4,0,2,0,)|"
        at org.openscience.cdk.layout.IdentityTemplateLibraryTest.encodeCoordinates(IdentityTemplateLibraryTest.java:61)

[INFO] Running org.openscience.cdk.layout.TemplateHandlerTest
[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.123 s <<< FAILURE! - in org.openscience.cdk.layout.TemplateHandlerTest
[ERROR] convert(org.openscience.cdk.layout.TemplateHandlerTest)  Time elapsed: 0.018 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is "C1C2CC3CC1CC(C2)C3 |(-1.07,-1.59,;.38,-1.21,;1.82,-1.59,;1.07,-.29,;-.38,-.67,;-1.82,-.29,;-1.82,1.21,;-.37,1.59,;.38,.29,;1.07,1.21,)|\nC12C3C4C1C5C2C3C45 |(.62,-.99,;-.88,-1.12,;-1.23,.43,;.26,.57,;.88,1.12,;1.23,-.43,;-.26,-.57,;-.62,.98,)|\nC1C2CC3C4CC5CC(C14)C(C2)C3C5 |(-1.82,2.15,;-.37,2.53,;1.07,2.15,;1.07,.65,;-.38,.27,;-.38,-1.23,;.37,-2.53,;-1.07,-2.15,;-1.07,-.65,;-1.82,.65,;.38,-.27,;.38,1.23,;1.82,-.65,;1.82,-2.15,)|\nC1CCC2C(C1)CCC3C4CCCC4CCC23 |(-6.51,.72,;-6.51,-.78,;-5.22,-1.53,;-3.92,-.78,;-3.92,.72,;-5.22,1.47,;-2.62,1.47,;-1.32,.72,;-1.32,-.78,;-.02,-1.53,;1.41,-1.07,;2.29,-2.28,;1.41,-3.49,;-.02,-3.03,;-1.32,-3.78,;-2.62,-3.03,;-2.62,-1.53,)|\nC1CCCCCCCCCCCCC1 |(-.04,1.51,;1.26,.76,;1.26,-.74,;2.56,-1.49,;2.56,-2.99,;1.29,-3.72,;1.31,-5.29,;-.09,-5.89,;-1.34,-5.24,;-1.34,-3.74,;-2.63,-2.99,;-2.63,-1.49,;-1.34,-.74,;-1.34,.76,)|\n"
     but: was "C1C2CC3CC1CC(C2)C3 |(-1,07,-1,59,;,38,-1,21,;1,82,-1,59,;1,07,-,29,;-,38,-,67,;-1,82,-,29,;-1,82,1,21,;-,37,1,59,;,38,,29,;1,07,1,21,)|\nC12C3C4C1C5C2C3C45 |(,62,-,99,;-,88,-1,12,;-1,23,,43,;,26,,57,;,88,1,12,;1,23,-,43,;-,26,-,57,;-,62,,98,)|\nC1C2CC3C4CC5CC(C14)C(C2)C3C5 |(-1,82,2,15,;-,37,2,53,;1,07,2,15,;1,07,,65,;-,38,,27,;-,38,-1,23,;,37,-2,53,;-1,07,-2,15,;-1,07,-,65,;-1,82,,65,;,38,-,27,;,38,1,23,;1,82,-,65,;1,82,-2,15,)|\nC1CCC2C(C1)CCC3C4CCCC4CCC23 |(-6,51,,72,;-6,51,-,78,;-5,22,-1,53,;-3,92,-,78,;-3,92,,72,;-5,22,1,47,;-2,62,1,47,;-1,32,,72,;-1,32,-,78,;-,02,-1,53,;1,41,-1,07,;2,29,-2,28,;1,41,-3,49,;-,02,-3,03,;-1,32,-3,78,;-2,62,-3,03,;-2,62,-1,53,)|\nC1CCCCCCCCCCCCC1 |(-,04,1,51,;1,26,,76,;1,26,-,74,;2,56,-1,49,;2,56,-2,99,;1,29,-3,72,;1,31,-5,29,;-,09,-5,89,;-1,34,-5,24,;-1,34,-3,74,;-2,63,-2,99,;-2,63,-1,49,;-1,34,-,74,;-1,34,,76,)|\n"
        at org.openscience.cdk.layout.TemplateHandlerTest.convert(TemplateHandlerTest.java:195)

[INFO] Running org.openscience.cdk.layout.HydrogenPlacerTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.071 s - in org.openscience.cdk.layout.HydrogenPlacerTest
[INFO] Running org.openscience.cdk.layout.AtomPlacerTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.openscience.cdk.layout.AtomPlacerTest
[INFO] Running org.openscience.cdk.layout.OverlapResolverTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 s - in org.openscience.cdk.layout.OverlapResolverTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   IdentityTemplateLibraryTest.encodeCoordinates:61 
Expected: is "|(12.5,5.5,;4.0,2.0,)|"
     but: was "|(12,5,5,5,;4,0,2,0,)|"
[ERROR]   IdentityTemplateLibraryTest.encodeEntry:71 
Expected: is "CO |(12.5,5.5,;4.0,2.0,)|"
     but: was "CO |(12,5,5,5,;4,0,2,0,)|"
[ERROR]   IdentityTemplateLibraryTest.store:128 
Expected: is "[C][C][O] |(.0,1.0,;2.0,3.0,;4.0,5.0,)|\n[C][C] |(.0,1.0,;2.0,3.0,)|\n"
     but: was "[C][C][O] |(,0,1,0,;2,0,3,0,;4,0,5,0,)|\n[C][C] |(,0,1,0,;2,0,3,0,)|\n"
[ERROR]   TemplateHandlerTest.convert:195 
Expected: is "C1C2CC3CC1CC(C2)C3 |(-1.07,-1.59,;.38,-1.21,;1.82,-1.59,;1.07,-.29,;-.38,-.67,;-1.82,-.29,;-1.82,1.21,;-.37,1.59,;.38,.29,;1.07,1.21,)|\nC12C3C4C1C5C2C3C45 |(.62,-.99,;-.88,-1.12,;-1.23,.43,;.26,.57,;.88,1.12,;1.23,-.43,;-.26,-.57,;-.62,.98,)|\nC1C2CC3C4CC5CC(C14)C(C2)C3C5 |(-1.82,2.15,;-.37,2.53,;1.07,2.15,;1.07,.65,;-.38,.27,;-.38,-1.23,;.37,-2.53,;-1.07,-2.15,;-1.07,-.65,;-1.82,.65,;.38,-.27,;.38,1.23,;1.82,-.65,;1.82,-2.15,)|\nC1CCC2C(C1)CCC3C4CCCC4CCC23 |(-6.51,.72,;-6.51,-.78,;-5.22,-1.53,;-3.92,-.78,;-3.92,.72,;-5.22,1.47,;-2.62,1.47,;-1.32,.72,;-1.32,-.78,;-.02,-1.53,;1.41,-1.07,;2.29,-2.28,;1.41,-3.49,;-.02,-3.03,;-1.32,-3.78,;-2.62,-3.03,;-2.62,-1.53,)|\nC1CCCCCCCCCCCCC1 |(-.04,1.51,;1.26,.76,;1.26,-.74,;2.56,-1.49,;2.56,-2.99,;1.29,-3.72,;1.31,-5.29,;-.09,-5.89,;-1.34,-5.24,;-1.34,-3.74,;-2.63,-2.99,;-2.63,-1.49,;-1.34,-.74,;-1.34,.76,)|\n"
     but: was "C1C2CC3CC1CC(C2)C3 |(-1,07,-1,59,;,38,-1,21,;1,82,-1,59,;1,07,-,29,;-,38,-,67,;-1,82,-,29,;-1,82,1,21,;-,37,1,59,;,38,,29,;1,07,1,21,)|\nC12C3C4C1C5C2C3C45 |(,62,-,99,;-,88,-1,12,;-1,23,,43,;,26,,57,;,88,1,12,;1,23,-,43,;-,26,-,57,;-,62,,98,)|\nC1C2CC3C4CC5CC(C14)C(C2)C3C5 |(-1,82,2,15,;-,37,2,53,;1,07,2,15,;1,07,,65,;-,38,,27,;-,38,-1,23,;,37,-2,53,;-1,07,-2,15,;-1,07,-,65,;-1,82,,65,;,38,-,27,;,38,1,23,;1,82,-,65,;1,82,-2,15,)|\nC1CCC2C(C1)CCC3C4CCCC4CCC23 |(-6,51,,72,;-6,51,-,78,;-5,22,-1,53,;-3,92,-,78,;-3,92,,72,;-5,22,1,47,;-2,62,1,47,;-1,32,,72,;-1,32,-,78,;-,02,-1,53,;1,41,-1,07,;2,29,-2,28,;1,41,-3,49,;-,02,-3,03,;-1,32,-3,78,;-2,62,-3,03,;-2,62,-1,53,)|\nC1CCCCCCCCCCCCC1 |(-,04,1,51,;1,26,,76,;1,26,-,74,;2,56,-1,49,;2,56,-2,99,;1,29,-3,72,;1,31,-5,29,;-,09,-5,89,;-1,34,-5,24,;-1,34,-3,74,;-2,63,-2,99,;-2,63,-1,49,;-1,34,-,74,;-1,34,,76,)|\n"
[INFO] 
[ERROR] Tests run: 114, Failures: 4, Errors: 0, Skipped: 0
[INFO] 
[ERROR] There are test failures.

Please refer to /home/egonw/var/Projects/hub/cdk/tool/sdg/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[INFO] 
[INFO] --- maven-jar-plugin:2.2:jar (default-jar) @ cdk-sdg ---
[INFO] 
[INFO] --- maven-jar-plugin:2.2:test-jar (default) @ cdk-sdg ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ cdk-sdg ---
[INFO] Installing /home/egonw/var/Projects/hub/cdk/tool/sdg/target/cdk-sdg-2.3-SNAPSHOT.jar to /home/egonw/.m2/repository/org/openscience/cdk/cdk-sdg/2.3-SNAPSHOT/cdk-sdg-2.3-SNAPSHOT.jar
[INFO] Installing /home/egonw/var/Projects/hub/cdk/tool/sdg/pom.xml to /home/egonw/.m2/repository/org/openscience/cdk/cdk-sdg/2.3-SNAPSHOT/cdk-sdg-2.3-SNAPSHOT.pom
[INFO] Installing /home/egonw/var/Projects/hub/cdk/tool/sdg/target/cdk-sdg-2.3-SNAPSHOT-tests.jar to /home/egonw/.m2/repository/org/openscience/cdk/cdk-sdg/2.3-SNAPSHOT/cdk-sdg-2.3-SNAPSHOT-tests.jar
[INFO] 
```

I would explore whitespace-platform differences first...

**Comment by egonw** [comment]
Oh, I see one issue now: Locale issue, see this diff:

```
[ERROR]   IdentityTemplateLibraryTest.store:128 
Expected: is "[C][C][O] |(.0,1.0,;2.0,3.0,;4.0,5.0,)|\n[C][C] |(.0,1.0,;2.0,3.0,)|\n"
     but: was "[C][C][O] |(,0,1,0,;2,0,3,0,;4,0,5,0,)|\n[C][C] |(,0,1,0,;2,0,3,0,)|\n"
```

**Comment by egonw** [comment]
it seems we need to update the code to output number in Locale.EN specifically...

**Comment by egonw** [comment]
(sorry, new laptop, and still has bits of Dutch locale :)

**Comment by johnmay** [comment]
Yep, but use Local.ROOT.

**Pull request closed without merging**
