### PR TITLE
Patch/mm2 test fixes

### PR DESCRIPTION
**Pull request by johnmay**
Resolves errors/failures in the MM2 atom type matcher. The problems was some brittle code that was doing minimal ring classification. 

Only one failure now which is not all atom types are tested. From looking at the code I believe we should deprecate this class (and perhaps AtomTypeTools) since it's not complete and uses several bad patterns. I've fixed it in case someone does want it but the deprecation would discourage it's use.

### CODE REVIEW

**Comment by johnmay** [comment]
Added extra commit at reviewer discretion to apply.

**Comment by egonw** [comment]
BTW, these two classes I never got around to porting to the new framework, i.e. idea of minimizing the amount of atom typing code, and it exists from times when we did not have all the library code we have now, and were stuck with ad hoc solutions...

**Comment by egonw** [comment]
The first four are applied, being tested, and soon to be pushed.

**Comment by johnmay** [comment]
Fixed last one - the MMFF94 was already deprecate but not moved.

**Comment by johnmay** [comment]
Have fixed last commit.

**Comment by egonw** [comment]
Applied and pushed.

**Pull request closed without merging**
