### PR TITLE
Testdata split

### PR DESCRIPTION
**Pull request by johnmay**
Splitting out (and then removing) testdata dependency from test code. This will mean we no longer need to install test-jar files. We could of technically done this anyways with some better config but convention of Maven is to put the test data where you need it - which is what we now have.

### CODE REVIEW

**Comment by johnmay** [comment]
Note: NCI_feb03_2D.mol2.gz should probably be removed (large file)

**Comment by egonw** [comment]
@johnmay, good to go (to review)?

**Comment by johnmay** [comment]
Okay now good to go. Here's what it's done :-).

We've reduced the "install" / "deploy" footprint from 46MB to 8.8MB. Build time (no tests) is about the same.

```
% mvn install -o -DskipTests
[INFO] Total time:  11.401 s
[INFO] Finished at: 2021-12-29T15:10:13Z
[INFO] ------------------------------------------------------------------------
% find ~/.m2/repository/org/openscience/cdk/* -name '*.jar' | xargs du -shc | tail -n1
 46M    total
```

```
% rm -rf ~/.m2/repository/org/openscience/cdk/*
% mvn install -o -DskipTests
[INFO] Total time:  9.781 s
[INFO] Finished at: 2021-12-29T15:11:42Z
[INFO] ------------------------------------------------------------------------
[john@sentinel:cdk]% find ~/.m2/repository/org/openscience/cdk/* -name '*.jar' | xargs du -shc | tail -n1
8.8M    total
```

**Comment by egonw** [comment]
@johnmay, I get this error:

```shell
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project cdk-qsarionpot: groups/excludedGroups require TestNG, JUnit48+ or JUnit 5 on project test classpath -> [Help 1]
```

**Comment by johnmay** [comment]
Clean build? The GitHub actions are all okay

**Comment by johnmay** [comment]
Qsar ion pot was removed since it was an empty module

**Review by egonw — APPROVED** [review]
Looks good to me. Thanks for this massive cleanup.

**Comment by johnmay** [comment]
More to come but I think this was by far the biggest

**Pull request merged**
