### PR TITLE
Modified breakExtractor to allow more formulas

### PR DESCRIPTION
**Pull request by ficolas2**
Modified breakExtractor to allow formulas with more elements after the parenthesis multiplier, and formulas with more than one parenthesis, like (BiO)2(CO3)

### CODE REVIEW

**Comment by johnmay** [comment]
Could you add a test to MolecularFormulaTest.
Also the multiplier may be more than a single character right, that should be handled?

**Comment by ficolas2** [comment]
So, I remade the breakExtractor method using regex, halving the line count, removing many nested conditionals, and making the code way cleaner compared to the solution I had previously.
Is there any reason regex wasnt used before?
Btw, about the automatic checks commits, I havent managed to set up the maven build in InteliJ IDEA, "Cannot find symbol" everywhere, will try again if I do more PRs I guess.

**Comment by johnmay** [comment]
Thanks for updating but I would prefer to go with the original change. This is in an appropriate use for a REGEX. The regex will be marginally slower but mainly I would have to disagree its cleaner. The addition of your huge comment should be a sign of this. I'll take the original commit you made and make the necessary changes.

In general you should use REGEX for matching, for parsing here is a good starting point:
https://en.wikipedia.org/wiki/Recursive_descent_parser

**Comment by ficolas2** [comment]
In that case, there is the non regex approach I made that supports nested brackets.

**Comment by johnmay** [comment]
Thanks looks great

**Pull request merged**
