### PR TITLE
Patch/egonw patches

### PR DESCRIPTION
**Pull request by johnmay**
Can't checkout from egonw/cdk so here are updated patches from yapchunwei. Could also change author with fixup.

### CODE REVIEW

**Comment by johnmay** [comment]
Hmmm... can't change author.. looking back at history it has

 yapchunwei <egonw@users.sourceforge.net>

Hence showing up as egon

**Comment by egonw** [comment]
Did you try:

git commit --amend --author="" ?

Otherwise, you can even try to just edit the patch text file...

**Comment by johnmay** [comment]
Yep but have a look at the log...

 git log --format='%aN <%cE>' | sort -u | grep yapchunwei

**Comment by egonw** [comment]
Mmmm...

**Pull request closed without merging**
