### PR TITLE
Added missing exception

### PR DESCRIPTION
**Pull request by rajarshi**

### CODE REVIEW

**Comment by johnmay** [comment]
Intentional runtime exception. How can you expect to recover from it?

**Comment by johnmay** [comment]
Note you can call ``cyclic`` manually if needed, but if the atom isn't in the molecule something is very wrong. Which code was triggering it?

**Comment by rajarshi** [comment]
I tried a clean compile and the maven build stopped on this

**Comment by egonw** [comment]
I think if the code can throw an exception (line 225), then the method signature needs to declare that, right?

**Comment by rajarshi** [comment]
From the [Javadocs](https://docs.oracle.com/javase/8/docs/api/java/lang/RuntimeException.html)

```
RuntimeException and its subclasses are unchecked exceptions. Unchecked exceptions do not need to be declared in a method or constructor's throws clause if they can be thrown by the execution of the method or constructor and propagate outside the method or constructor boundary.
```

**Comment by rajarshi** [comment]
OK - my bad. Didn't do a `mvn clean`. Fresh `clean` and `package` works OK. Closing this pull

**Comment by johnmay** [comment]
Glad this is resolved but please remember checked exceptions are the root of all evil :-). Best to try and design code to avoid exceptions all together unless you really can't avoid them. In this case you're forcing the user to handle something 100% of time for what is a programming error (typically what RunTimeExceptions are for. Could you imagine if you had to catch ``ArrayIndexOutOfBounds`` every time you access an array or a ``NullPointerException`` every time you called a method. Without run time exceptions you'd have this:

```java
try {
  int x = x[5];
} catch (ArrayIndexOutOfBounds e) {
}
```

```java
try {
mol.getAtomCount();
} catch (NullPointerException e) {
}
```

**Comment by johnmay** [comment]
*have to do this, it would not be optional if exceptions were declared in the signature.

**Pull request closed without merging**
