### PR TITLE
Core/data groups

### PR DESCRIPTION
**Pull request by johnmay**
Handling Data Sgroups in CXSMILES and MDL. These allow us to attach data (i.e. wt/%) to certain components.

### CODE REVIEW

**Comment by egonw** [comment]
I assume a new PR will be coming?

**Comment by johnmay** [comment]
Not sure why it closed... but yes minor issue to update

**Comment by johnmay** [comment]
Okay this is good to go now, non urgent

**Comment by egonw** [comment]
I'm a bit busy this week (first week back at work, so lot's of things to coordinate) and will look at it asap!

**Comment by johnmay** [comment]
@egonw Could I merge this in please :-)

**Comment by egonw** [comment]
yes, please go ahead. GitHub tells me there are some conflicts that need resolving, but I trust you.

**Review by egonw — APPROVED** [review]

**Comment by johnmay** [comment]
Yep I'll rebase first, thanks!

**Pull request merged**
