### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by egonw**

### CODE REVIEW

**Comment by johnmay** [comment]
Mockito broke the build :-)

**Comment by johnmay** [comment]
Mockito v5 is Java 11+ only so we can not use it. TBH really we should not use Mockito, it's caused more issues over the years than it help. Basically if you need to mock something it's not too hard to write a little stub which does what you need.

**Comment by egonw** [comment]
> Mockito broke the build :-)

Sorry, my bad. I'll remove that part.

> Basically if you need to mock something it's not too hard to write a little stub which does what you need.

Who introduced it? :)

Sounds perfect for something like a small open science grant.

**Comment by egonw** [comment]
@johnmay, should be okay now.

**Pull request merged**
