### PR TITLE
Two updated dependencies

### PR DESCRIPTION
**Pull request by egonw**

### CODE REVIEW

**Comment by johnmay** [comment]
Yeah the xml-apis ain't going to update :-). Tried before. Mockito should be fine though.

**Comment by egonw** [comment]
Withdrawing this PR. Apparently, it requires Java11 or higher. Not worth it right now.

**Comment by egonw** [comment]
> Yeah the xml-apis ain't going to update :-). Tried before. Mockito should be fine though.

@johnmay, feel free to cherry-pick the mickito patch, or just update it yourself :)

**Comment by johnmay** [comment]
I don't think it's Java 11 rather just like Logging Java XML is a mess

**Comment by johnmay** [comment]
I think it's the combination with xerces....

**Comment by uli-f** [comment]
The whole XML parsing in Java is a bit similar to the world of logging in Java. There is a standard that usually comes in the packaged form of a jar with interfaces and then there are also jars that deliver the implementation.

Without knowing/remembering all the details: There were changes with different Java versions (i.e., Java having its own XML parser implementation in earlier versions and then dropping/changing that or something similar).

Irrespective of that, I have two excludes in my dependency graph to get it to compile and run without exceptions:
```
exclude group: 'xerces', module: 'xercesImpl'
exclude group: 'com.sun.xml.stream', module: 'sjsxp'
```

**Comment by johnmay** [comment]
To get what to compile and run without exception? The build? Working fine on Linux/OS X - is it still broken on Windows?

The xml deps are much harder to remover than logging.

**Comment by uli-f** [comment]
> To get what to compile and run without exception? The build? Working fine on Linux/OS X - is it still broken on Windows?

Sorry, that was a bit unspecific. No worries, it works fine on Windows!

I have other dependencies in my project and they bring in XML libraries as transitive dependencies. At one point - without remembering all the details - that got really messy and I had to exclude some of those XML libs from my dependency graph.

All I wanted to express is my agreement that having different XML libraries as a dependency can get messy in bigger projects.

**Comment by johnmay** [comment]
No worries, yeah the xerces is the big issue. Normally for XML I would use Woodstox/STAX but it’s more manual to parse bits

**Pull request closed without merging**
