### PR TITLE
Update test timeout to 1000 ms

### LINKED ISSUE #285: timing regression in the MF generator
@tomas-pluskal, can you please have a look at this regression?

image

I happens not in my local Eclipse but on Jenkins: https://jenkins.bigcat.unimaas.nl/job/cdk/lastCompletedBuild/testReport/org.openscience.cdk.formula/MolecularFormulaGeneratorTest/testCancel/

Do you see an option to ensure all required classes are loaded before the cancelling is tested?

### PR DESCRIPTION
**Pull request by tomas-pluskal**
Hope this fixes #285

### CODE REVIEW

**Comment by egonw** [comment]
OK, yes, that should do it too. I was kinda hoping that preloading the class it is busy with loading would solve it more nicely...

**Comment by johnmay** [comment]
-1

**Comment by egonw** [comment]
Shall I revert the patch, so that we can think of a better way of fixing the regression?

Who approved that test in the first place?? ;)

**Comment by johnmay** [comment]
It's fine, I just don't like it :-). As it's in a test I'm not really bothered.

**Comment by egonw** [comment]
Agreed... see my comments that I had hoped for a more elegant fix... but cannot think of one right now...

**Pull request merged**
