### PR TITLE
Updated the log4j library dependency

### PR DESCRIPTION
**Pull request by egonw**
Updates the Log4J library version of the dependency.

### CODE REVIEW

**Comment by johnmay** [comment]
Meh

**Comment by johnmay** [comment]
I don't think the API actually includes the implementation no?

**Comment by johnmay** [comment]
Probably okay though as the downstream would just include logj4-core

**Comment by egonw** [comment]
Ah, that dep could be included in cdk-log4j. Shall I add that patch?

**Comment by egonw** [comment]
BTW, related to this, I was surprised with the high number of modules that depend on it. Only that cdk-log4j module should, really.

**Comment by johnmay** [comment]
So most of them are scope test and it's needed so when you run the tests you can get log messages. But I think you're right we can probable drop those and just make sure cdk-log4j is included.

**Comment by johnmay** [comment]
Did you rename the branch... restart build keeps failing.

**Comment by johnmay** [comment]
Okay Travis is confused as you pushed only to egonw account... would think it could handle that. Going to merge and then see if works on master.

**Comment by johnmay** [comment]
```
12:57:33.966 [main] WARN  org.openscience.cdk.tools.LoggingToolTest - org.openscience.cdk.tools.LoggingToolTest@2f177a4borg.openscience.cdk.tools.LoggingToolTest@2f177a4b
12:57:33.972 [main] WARN  org.openscience.cdk.tools.LoggingToolTest - org.openscience.cdk.tools.LoggingToolTest@56de5251org.openscience.cdk.tools.LoggingToolTest@56de5251org.openscience.cdk.tools.LoggingToolTest@56de5251org.openscience.cdk.tools.LoggingToolTest@56de5251
12:57:33.973 [main] FATAL org.openscience.cdk.tools.LoggingToolTest - org.openscience.cdk.tools.LoggingToolTest@419c5f1a
12:57:33.974 [main] WARN  org.openscience.cdk.tools.LoggingToolTest - org.openscience.cdk.tools.LoggingToolTest@12b0404forg.openscience.cdk.tools.LoggingToolTest@12b0404forg.openscience.cdk.tools.LoggingToolTest@12b0404f
12:57:33.979 [main] WARN  org.openscience.cdk.tools.LoggingToolTest - org.openscience.cdk.tools.LoggingToolTest@5276e6b01.0
12:57:33.982 [main] WARN  org.openscience.cdk.tools.LoggingToolTest - org.openscience.cdk.tools.LoggingToolTest@71b1176borg.openscience.cdk.tools.LoggingToolTest@71b1176borg.openscience.cdk.tools.LoggingToolTest@71b1176borg.openscience.cdk.tools.LoggingToolTest@71b1176borg.openscience.cdk.tools.LoggingToolTest@71b1176b
12:57:33.983 [main] WARN  org.openscience.cdk.tools.LoggingToolTest - org.openscience.cdk.tools.LoggingToolTest@6193932a1
12:57:33.983 [main] ERROR org.openscience.cdk.tools.LoggingToolTest - org.openscience.cdk.tools.LoggingToolTest@647fd8ceorg.openscience.cdk.tools.LoggingToolTest@647fd8ceorg.openscience.cdk.tools.LoggingToolTest@647fd8ceorg.openscience.cdk.tools.LoggingToolTest@647fd8ce
12:57:33.985 [main] ERROR org.openscience.cdk.tools.LoggingToolTest - org.openscience.cdk.tools.LoggingToolTest@159f197org.openscience.cdk.tools.LoggingToolTest@159f197org.openscience.cdk.tools.LoggingToolTest@159f197org.openscience.cdk.tools.LoggingToolTest@159f197org.openscience.cdk.tools.LoggingToolTest@159f197
```

**Pull request merged**
