### PR TITLE
Patch/phase out get symbol 2

### PR DESCRIPTION
**Pull request by xperrylinn**
The third patch for replacing getSymbol String equality statements with getAtomicNumber and IElement element enum in the qsarmolecular module. There's a bit more work to do in the qsarmolecular module and some of the getSymbol statements will more be challenging to replace. For example, some instances of atom.getSymbol are compared against a string type method parameter or hardcoded class/instance variable. It seems like updating these instances might require changing the API, i.e. method params, or incorporating logic to map string params to IElement atomic numbers.

Test 367, 1274, 1429, 1596 in XLogPDescriptorTest are failing because of a NullPointerException (line 887 in XLogPDescriptor) where QueryAtom from type does not have it's atomicNumber set. See the lines below:

```
            QueryAtomContainer aminoAcid = QueryAtomContainerCreator.createBasicQueryContainer(createAminoAcid(ac
                    .getBuilder()));

            Iterator bonds = aminoAcid.bonds().iterator();

```

The atoms in each of the bonds from ```aminoAcid.bonds().iterator();``` have atomicNumber null. I haven't fully debugged it yet, but I'm open to looking into it. Thoughts?

On that note of test, does the cdk have continuous integration that checks for test during PRs? I noticed the green "Able to Merge" prompt below, but what surprised by this despite failing tests.

Screen Shot 2020-07-08 at 1 02 37 PM

### CODE REVIEW

**Comment by egonw** [comment]
Yes, I think so. The Travis-CI normally also gets run on branches, and this includes the testing, per https://github.com/cdk/cdk/blob/master/.travis.yml

But something seems to go wrong: https://travis-ci.org/github/cdk/cdk/builds/706295891 And not sure why that doesn't show up here in the PR...

**Comment by egonw** [comment]
BTW. it may not be the branch that fails because of the new patches... master fails too: https://travis-ci.org/github/cdk/cdk/builds/705855840

**Comment by egonw** [comment]
I added a bug report: https://github.com/cdk/cdk/issues/650

**Comment by johnmay** [comment]
This is where switching to int rather than integer would help. In this case the query container has query atoms which don't have an atomic number, 0 would be fine though. We could use ``Objects.equal()`` in that class but more the question is why it is trying to check Atomic Number of query objects.

**Comment by xperrylinn** [comment]
In stepping through the failing test with a debugger, I can confirm that QueryAtom objects with null atomicNumber are being instantiated in QueryAtomContainer from an AtomContainer instance with atoms that have their atomicNumber set. I'm not familiar with the expected behavior of Query.* objects, but should QueryAtoms have their atomic number set if it's known?

**Comment by xperrylinn** [comment]
> more the question is why it is trying to check Atomic Number of query objects.

It's looking up the atomic number of atoms in QueryBond, in order to replace it with new QueryBond that's different from the default instantiation spec in QueryAtomContainer. 

Specifically, it's searching for the alpha carbon amine group bond, so it can replaced with a new QueryBond instance that has the following spec: `QueryBond(bondAtom0, bondAtom1, Expr.Type.SINGLE_OR_AROMATIC)`. The context for this check is that the amino acid QueryAtomContainer is used to search an AtomContainer for the presence of an amino acid sub structure.

**Comment by johnmay** [comment]
Sorry not had to time to look at this, the naive fix is to just set the atomic number in the query atom container creator. However the real issue is still the class is abusing the query in some way but I need to look at it closely to see why and how to change it

**Comment by johnmay** [comment]
Okay belt and braces, first of I did expect this before and hence has a comment in the QueryAtomContainer.
```
            // backward compatibility for naughty methods that are expecting
            // these to be set for a query!
```
I now also set the atomic number - #655. However the real fix is started in #656 which removes some bad logic from the descriptor.

The other thing I realised is the QueryAtoms aren't like the normal atoms and still have a symbol and an atomic num. Ideally they were reuse as much as possible underneath but it's not that way.

**Comment by xperrylinn** [comment]
Excellent! Thanks for the support. Looks like all checks have passed now. I'll open a new PR to wrap up getSymbol changes in qsarmolecular.

**Comment by johnmay** [comment]
This okay to merge?

**Comment by xperrylinn** [comment]
Yep yep

**Pull request merged**
