### PR TITLE
Watch out for NULL charges

### PR DESCRIPTION
**Pull request by johnmay**
Fixed #370

### CODE REVIEW

**Comment by johnmay** [comment]
*grumble* *grumble* *grumble* annoying atom types, feel free to propose a fix @egonw - I would rather just remove the entire perception code :-)

**Comment by egonw** [comment]
> _grumble_ _grumble_ _grumble_ annoying atom types, feel free to propose a fix @egonw - I would rather just remove the entire perception code :-)

Yeah, I hear you: "SMILES rules". If the input format has atom types, then you do not need the perceive atom types. Unfortunately, we still support plenty of input formats that do not, or use different atom types then SMILES. Think PDB, Sybyl, XYZ, a chemist drawing something in an editor, ...

**Comment by johnmay** [comment]
I think the test failure is quite simple and comes down to if null is the same as 0 charge. It seems like the atomtyper wants to consider this so whilst elsewhere (in the test failure) this counts as a change

**Comment by egonw** [comment]
> I think the test failure is quite simple and comes down to if null is the same as 0 charge. It seems like the atomtyper wants to consider this so whilst elsewhere (in the test failure) this counts as a change

Oh, that reply was independent from the patch.

**Comment by johnmay** [comment]
Ek there were failing unit tests! Sorry should have flagged as WIP

**Pull request merged**
