### PR TITLE
Fix/pmd warnings

### PR DESCRIPTION
**Pull request by egonw**
John, more code clean up. Of more interest are the fourth and last patch.

### CODE REVIEW

**Comment by johnmay** [comment]
All good - for the PMD ones - am merging from GitHub. Once we update java3d API will start making a release.

**Comment by egonw** [comment]
Regarding, java3d.... anything I can do?

**Comment by johnmay** [comment]
See pull request - thought I added it the other day but forgot.

**Comment by johnmay** [comment]
Oh actually need to give you the correct setup details for PMD - I had it at the EBI but that server is now down. I think it was mainly for the ignores.

**Pull request merged**
