### PR TITLE
Patch/cxsmiles read

### PR DESCRIPTION
**Pull request by johnmay**
1) A few patches on rendering that we left behind from another branch.
2) Read CXSMILES layers and set information in CDK data-structures (Main part).

### CODE REVIEW

**Comment by egonw** [comment]
BTW, what is a CXSMILES?

**Comment by johnmay** [comment]
CXSMILES (ChemAxon Extended SMILES) is layers of info in the SMILES title that add additional semantics - think of it like an InChI AuxInfo but unlike the AuxInfo you can still canonicalise it.

```
CCC |(x,y,z;x,y,z;x,y,z)| coords
*C* |$_AP1;;Y'$| atom labels
```

It allows the extension of SMILES to support additional features whilst maintaining backwards compatibility. Indigo (GGA/EPAM) already have support for some features such as fragment grouping and atom labels.

From discussions with a former ChemAxon dev, it wasn't intended for external consumption and just for JChemBase. Despite some horrid syntax (reusing ',' for field and record separation) it is actually quite useful. Projects such as HELM use the atom-labels (although they could have done that another way).

**Comment by egonw** [comment]
Did you create an IChemFormat subclassing the SMILESFormat?

**Comment by johnmay** [comment]
They're not really a different format. Every CXSMILES is a valid SMILES. Would you consider reactions SMILES and SMILES different? It's perfectly valid to mix these in a single file:

```
CN1C=NC2=C1C(=O)N(C(=O)N2C)C caffeine
CCO.CC(=O)O>[H+]>CC(=O)OCC.O 
*CC |$R'$|
>>*CC |$R'$|
```

**Comment by egonw** [comment]
If every CXSMILES is indeed a valid SMILES, then it's fine, I guess... yet, not every full SMILES parser may parse full CXSMILES, I guess? But if any SMILES parser will safely ignore the CX bits, then it should indeed be no problem.

**Comment by johnmay** [comment]
Yep, the coordinate output will be very useful. I've previously documented how to do it in a custom way in the JavaDoc of [SmilesGenerator](http://cdk.github.io/cdk/1.5/docs/api/index.html?org/openscience/cdk/smiles/SmilesGenerator.html) but have a more portable way makes this much easier.

**Comment by johnmay** [comment]
Some updates:

Minimum arrow width padding, before:
image
Now
image

Conditions drawn below the arrow:

image

**Comment by johnmay** [comment]
Cool thanks, do you have any commits pending? Otherwise I think it's time for a release.

**Comment by egonw** [comment]
No, but the next two weeks I'm taking a number of days off and plan to work on the CDK paper and possible my CDK book... that will likely results in some patches, but that's fine for a later release.

**Pull request merged**
