### PR TITLE
Added a test+fix for isotope pattern generation for C10000

### PR DESCRIPTION
**Pull request by tomas-pluskal**
The test is failing at the moment due to NullPointerException somewhere in IsotopePatternManipulator

```
java.lang.NullPointerException
	at org.openscience.cdk.formula.IsotopePatternManipulator.sortByMass(IsotopePatternManipulator.java:131)
	at org.openscience.cdk.formula.IsotopePatternGenerator.getIsotopes(IsotopePatternGenerator.java:113)
	at org.openscience.cdk.formula.IsotopePatternGeneratorTest.testCalculateIsotopesC10000(IsotopePatternGeneratorTest.java:266)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

### CODE REVIEW

**Comment by johnmay** [comment]
Can you help with the fix, don't like adding tests for stuff without a fix otherwise they just ignored.

I can fix the the NPE by making [this value](https://github.com/cdk/cdk/blob/master/tool/formula/src/main/java/org/openscience/cdk/formula/IsotopePatternManipulator.java#L122) `Double.Max`.

But then the assertion on number of isotopes fails...

```
java.lang.AssertionError: 
Expected :98
Actual   :44
```

Any ideas?

**Comment by johnmay** [comment]
Also ouch that N^2 sort... in sortByMass

**Comment by tomas-pluskal** [comment]
I guess 44 is the correct result. I didn't realize the intensities were in the scale 0 to 1.
I will commit a fix.

**Comment by tomas-pluskal** [comment]
Fix added

**Comment by johnmay** [comment]
Looks good, don't see any failures. Thanks

**Pull request merged**
