### PR TITLE
Bad SMILES are marked with an empty molecule and property. This mirro…

### PR DESCRIPTION
**Pull request by johnmay**
…rs behaviour of the IteratingSMILESReader.

### CODE REVIEW

**Comment by egonw** [comment]
John, Travis fails because of too much output during the testing phase... I am a bit puzzled as to why, as this did not seem to be a problem when run on my copy... but I will turn one debug info output and then look at this bugfix...

**Comment by egonw** [comment]
OK, I think I found the reason :) (See commit on master)

**Comment by egonw** [comment]
@johnmay OK, your patches changes the API according to a now broken test: SMILESReaderTest.testReadingSmiFile_2() which expects that if there was no name defined in the file, no property is set. Your code now sets it, but as an empty string, causing this fail:

    java.lang.AssertionError: expected null, but was:<>
            at org.junit.Assert.fail(Assert.java:88)
            at org.junit.Assert.failNotNull(Assert.java:664)
            at org.junit.Assert.assertNull(Assert.java:646)
            at org.junit.Assert.assertNull(Assert.java:656)
            at org.openscience.cdk.io.SMILESReaderTest.testReadingSmiFile_2(SMILESReaderTest.java:101)

Can you let me know as release manager, what you opt for? Update patch and keep behavior, or keep this patch and change the behavior?

Otherwise looks good.

**Comment by johnmay** [comment]
Hmm I'll update to existing - i'm guessing it's quite rare to have some entries with and without names (e.g. normally either all have names or none) so null makes sense.

**Comment by egonw** [comment]
Applied and pushed.

**Comment by johnmay** [comment]
travis++, Noel had previously showed me it on OB - good to see it's use.

**Pull request closed without merging**
