### PR TITLE
Fix for reading mol file with ALS lines into non-QueryAtomContainer

### PR DESCRIPTION
**Pull request by dkatzel-ncats**
if we read a  mol file containing `M  ALS` line(s) and write it to an `IAtomContainer` instead of a `IQueryAtomContainer` then the checks for avoiding atom typing won't see that that property parsing section converted some Atoms into QueryAtoms and trying to parse such mol files will error out with an error message "java.lang.IllegalArgumentException: an atom had an undefieind atomic number".

Added additional check just prior to atom typing to see if any atoms are QueryAtoms and added another test for this usecase.

### CODE REVIEW

**Comment by dkatzel-ncats** [comment]
I also noticed that when the ALS property creates the QueryAtom we lose the coordinates parsed for that atom index from the atom block.  Should we keep those?

**Comment by johnmay** [comment]
Should keep coords but you shouldn't really be able to read a query into a non query. We do "upgrade" it as such but really I think it's a bad API design and it shouldn't change what gets passed in. 

For example returning a bool would be nicer:
```
bool read(IAtomContainer mol);
```

Anyways will double check tomorrow but patch looks okay

**Comment by dkatzel-ncats** [comment]
ok I'll push a quick update to keep the coords then.  As for the  read with AtomContainer vs QueryContainer.  how do you know if you are taking in as input a user supplied mol if it will have query atoms/bonds or not until you parse it?

**Comment by johnmay** [comment]
> how do you know if you are taking in as input a user supplied mol if it will have query atoms/bonds or not until you parse it?

What happens if you try open a .DOC file with Excel :-).

Formerly a "query file" and "molecule file" are different, in real life databases mix and match which is annoying but generally if you tried to read a "molecule" and got a "query" you likely want to throw it out as now much you can do with it. We do have the ChemFile container concept which handles such cases but no mater which way you suck the lemon it's sour.

**Pull request merged**
