### PR TITLE
Fix bug in NeighborList and related test

### PR DESCRIPTION
**Pull request by Luckick**
Previously not all atoms are put into neighbor list, this will cause some points that are actually covered by atoms not get deleted, which cause the accessible surface points not accurate.
Now this issue gets fixed.

### CODE REVIEW

**Comment by johnmay** [comment]
Ideally best if you can isolate patches, this is easiest but doing the changes on separate branches.

**Comment by johnmay** [comment]
I've fixed the neighbour list in #558

**Comment by johnmay** [comment]
Replaced with #559

**Comment by Luckick** [comment]
Thank you!

**Pull request closed without merging**
